name: "gtf_filter"
info:
  migration_info:
    git_repo: https://github.com/nf-core/rnaseq.git
    paths: [modules/local/gtf_filter.nf]
    last_sha: 1c6012ecbb087014ea4b8f0f3d39b874850277a8
description: | 
  Filters a GTF file based on sequence names in a FASTA file.

argument_groups:
- name: "Input"
  arguments:
  - name: "--fasta"
    type: file
    description: Genome fasta file
  - name: "--gtf"
    type: file
    description: GTF file
  - name: "--skip_transcript_id_check"
    type: boolean_true
    description: Skip checking for transcript IDs in the GTF file.
  - name: "--versions"
    type: file
    must_exist: false
- name: " Output"
  arguments:
  - name: "--filtered_gtf"
    type: file
    direction: output
    description: Filtered GTF file containing only sequences in the FASTA file
  - name: "--updated_versions"
    type: file
    default: versions.yml
    direction: output

resources:
  - type: python_script
    path: script.py

test_resources:
  - type: bash_script
    path: test.sh
  - path: /testData/minimal_test/reference/genome.fasta
  - path: /testData/minimal_test/reference/genes.gtf.gz
  
engines:
  - type: docker
    image: python 
runners:
  - type: executable
  - type: nextflow