functionality:
  name: "prepare_multiqc_input"
  description: |
    Prepare directory with all the input files for MultiQC.

  argument_groups: 
    - name: "Input"
      arguments:
        - name: "--fail_trimming_multiqc"
          type: file
          must_exist: false
        - name: "--fail_mapping_multiqc"
          type: file
          must_exist: false
        - name: "--fail_strand_multiqc"
          type: file
          must_exist: false
        - name: "--fastqc_raw_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--fastqc_trim_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--trim_log_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--sortmerna_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
          required: false
        - name: "--star_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        # - name: "--hisat2_multiqc"
        #   type: file
        # - name: "--rsem_multiqc"
        #   type: file
        - name: "--salmon_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--samtools_stats"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--samtools_flagstat"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--samtools_idxstats"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--markduplicates_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--featurecounts_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--aligner_pca_multiqc"
          type: file
          must_exist: false
        - name: "--aligner_clustering_multiqc"
          type: file
          must_exist: false
        # - name: "--pseudoaligner_pca_multiqc"
        #   type: file
        # - name: "--pseudoaligner_clustering_multiqc"
        #   type: file
        - name: "--preseq_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--qualimap_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--dupradar_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--bamstat_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--inferexperiment_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--innerdistance_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--junctionannotation_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--junctionsaturation_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--readdistribution_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--readduplication_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false
        - name: "--tin_multiqc"
          type: file
          multiple: true
          multiple_sep: ","
          must_exist: false

    - name: "Ouput"
      arguments:
        - name: "--output"
          type: file
          direction: output
          default: multiqc_input
      
  resources:
    - type: bash_script
      path: script.sh

platforms:
  - type: docker
    image: ubuntu:22.04
  - type: nextflow