name: kallisto_quant
namespace: kallisto
info:
  migration_info:
    git_repo: https://github.com/nf-core/rnaseq.git
    paths: [modules/nf-core/kallisto/quant/main.nf, modules/nf-core/kallisto/quant/meta.yml]
    last_sha: aff1d2e02717247831644769fc3ba84868c3fdde
description: | 
  Computes equivalence classes for reads and quantifies abundances.

argument_groups: 
- name: "Input"
  arguments:
  - name: "--input"
    type: file
    multiple: true
    multiple_sep: ","
    description: List of input FastQ files of size 1 and 2 for single-end and paired-end data, respectively.
  - name: "--paired"
    type: boolean
    description: Paired reads or not.
  - name: "--strandedness"
    type: string
    description: Sample strand-specificity.
  - name: "--index"
    type: file
    description: Kallisto genome index.
  - name: "--gtf"
    type: file
    description: Optional gtf file for translation of transcripts into genomic coordinates.
  - name: "--chromosomes"
    type: file
    description: Optional tab separated file with chromosome names and lengths.
  - name: "--fragment_length"
    type: integer
    description: For single-end mode only, the estimated average fragment length.
  - name: "--fragment_length_sd"
    type: integer
    description: For single-end mode only, the estimated standard deviation of the fragment length.

- name: "Output"
  arguments:
  - name: "--output"
    type: file
    description: Kallisto quant results
    default: "$id.kallisto_quant_results"
    direction: output
  - name: "--log"
    type: file
    description: File containing log information from running kallisto quant
    default: "$id.kallisto_quant.log.txt"
    direction: output
  - name: "--run_info"
    type: file
    description: A json file containing information about the run
    default: "$id.run_info.json"
    direction: output 
  - name: "--quant_results_file"
    type: file
    description: TSV file containing abundance estimates from Kallisto
    direction: output
    default: $id.abundance.tsv

resources:
  - type: bash_script
    path: script.sh

test_resources:
  - type: bash_script
    path: test.sh
  - path: /testData/minimal_test/reference/transcriptome.fasta
  - path: /testData/minimal_test/input_fastq/SRR6357070_1.fastq.gz
  - path: /testData/minimal_test/input_fastq/SRR6357070_2.fastq.gz

engines:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: docker
        run: |
          apt-get update && \
          apt-get install -y --no-install-recommends wget && \
          wget --no-check-certificate https://github.com/pachterlab/kallisto/releases/download/v0.50.1/kallisto_linux-v0.50.1.tar.gz && \
          tar -xzf kallisto_linux-v0.50.1.tar.gz && \
          mv kallisto/kallisto /usr/local/bin/
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midmem, midcpu ]
