functionality:
  name: "salmon_summarizedexperiment"
  namespace: "salmon"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/local/salmon_summarizedexperiment.nf]
      last_sha: 0a1bdcfbb498987643b74e9fccab85ccd9f2a17d
  description: Create SummarizedExperiment object from Salmon counts

  arguments: 
    # Input
    - name: "--tpm_gene"
      type: file
    - name: "--counts_gene"
      type: file
    - name: "--counts_gene_length_scaled"
      type: file
    - name: "--counts_gene_scaled"
      type: file
    - name: "--tpm_transcript"
      type: file
    - name: "--counts_transcript"
      type: file
    - name: "--tx2gene_tsv"
      type: file

    # Output
    - name: "--output"
      type: file
      direction: output
      default: salmon_merged_summarizedexperiment
  
  resources:
    - type: bash_script
      path: script.sh
    # copied from https://github.com/nf-core/rnaseq/blob/3.12.0/bin/salmon_summarizedexperiment.r
    - path: salmon_summarizedexperiment.r
  test_resources:
    - type: bash_script
      path: test.sh
   
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: apt
        packages: [ r-base, libcurl4-openssl-dev ]
      - type: r
        bioc: [ SummarizedExperiment ]
  - type: nextflow