name: "pre_processing"
namespace: "workflows"
version: "main_build"
argument_groups:
- name: "Inputs"
  arguments:
  - type: "string"
    name: "--id"
    description: "ID of the sample."
    info: null
    example:
    - "foo"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fastq_1"
    description: "Path to the sample (or read 1 of paired end sample)."
    info: null
    example:
    - "input.fastq.gz"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fastq_2"
    description: "Path to read 2 of the sample."
    info: null
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--strandedness"
    description: "Sample strand-specificity. Must be one of unstranded, forward, reverse\
      \ or auto"
    info: null
    default:
    - "auto"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--bbsplit_index"
    description: "BBsplit index"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--bbsplit_fasta_list"
    description: "Path to comma-separated file containing a list of reference genomes\
      \ to filter reads against with BBSplit. To use BBSplit, \"--skip_bbsplit\" must\
      \ be explicitly set to \"false\". The file should contain 2 (comma separated)\
      \ columns - short name and full path to reference genome(s)"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--ribo_database_manifest"
    description: "Text file containing paths to fasta files (one per line) that will\
      \ be used to create the database for SortMeRNA."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--transcript_fasta"
    description: "Path to FASTA transcriptome file."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--gtf"
    description: "Path to GTF annotation file."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--salmon_index"
    description: "Path to directory containing the Salmon index"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--num_trimmed_reads"
    description: "Number of reads after trimming"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Extra pipeline options"
  arguments:
  - type: "boolean"
    name: "--skip_qc"
    description: "Skip QC steps of the workflow."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "FastQC options"
  arguments:
  - type: "boolean"
    name: "--skip_fastqc"
    description: "Skip FatQC step."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "UMI-tools options"
  arguments:
  - type: "boolean"
    name: "--with_umi"
    description: "Enable UMI-based read deduplication."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--skip_umi_extract"
    description: "Skip umi_tools extract step."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--umitools_extract_method"
    description: "UMI pattern to use."
    info: null
    default:
    - "string"
    required: false
    choices:
    - "string"
    - "regex"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--umitools_bc_pattern"
    description: "The UMI barcode pattern to use e.g. 'NNNNNN' indicates that the\
      \ first 6 nucleotides of the read are from the UMI."
    info: null
    default:
    - ""
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--umitools_bc_pattern2"
    description: "The UMI barcode pattern to use if the UMI is located in read 2."
    info: null
    default:
    - ""
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--umi_discard_read"
    description: "After UMI barcode extraction discard either R1 or R2 by setting\
      \ this parameter to 1 or 2, respectively."
    info: null
    default:
    - 0
    required: false
    choices:
    - 0
    - 1
    - 2
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--umitools_umi_separator"
    description: "The character that separates the UMI in the read name. Most likely\
      \ a colon if you skipped the extraction with UMI-tools and used other software."
    info: null
    default:
    - "_"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--umitools_grouping_method"
    description: "Method to use to determine read groups by subsuming those with similar\
      \ UMIs. All methods start by identifying the reads with the same mapping position,\
      \ but treat similar yet nonidentical UMIs differently."
    info: null
    default:
    - "directional"
    required: false
    choices:
    - "unique"
    - "percentile"
    - "cluster"
    - "adjacency"
    - "directional"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--save_umi_intermeds"
    description: "If this option is specified, intermediate FastQ and BAM files produced\
      \ by UMI-tools are also saved in the results directory."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Read trimming options"
  arguments:
  - type: "string"
    name: "--trimmer"
    description: "Specify the trimming tool to use."
    info: null
    default:
    - "trimgalore"
    required: false
    choices:
    - "trimgalore"
    - "fastp"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--extra_trimgalore_args"
    description: "Extra arguments to pass to Trim Galore! command in addition to defaults\
      \ defined by the pipeline."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--extra_fastp_args"
    description: "Extra arguments to pass to fastp command in addition to defaults\
      \ defined by the pipeline."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--min_trimmed_reads"
    description: "Minimum number of trimmed reads below which samples are removed\
      \ from further processing. Some downstream steps in the pipeline will fail if\
      \ this threshold is too low."
    info: null
    default:
    - 10000
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--skip_trimming"
    description: "Skip the adapter trimming step."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--save_trimmed"
    description: "Save the trimmed FastQ files in the results directory."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Alignment options"
  arguments:
  - type: "string"
    name: "--extra_salmon_quant_args"
    description: "Extra arguments to pass to salmon quant command in addition to defaults\
      \ defined by the pipeline."
    info: null
    default:
    - ""
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Read filtering options"
  arguments:
  - type: "boolean"
    name: "--skip_bbsplit"
    description: "Skip BBSplit for removal of non-reference genome reads."
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--remove_ribo_rna"
    description: "Enable the removal of reads derived from ribosomal RNA using SortMeRNA."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Other options"
  arguments:
  - type: "string"
    name: "--extra_fq_subsample_args"
    description: "Extra arguments to pass to fq subsample command in addition to defaults\
      \ defined by the pipeline."
    info: null
    default:
    - "--record-count 1000000 --seed 1"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--versions"
    info: null
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Output"
  arguments:
  - type: "file"
    name: "--qc_output1"
    description: "Path to output directory"
    info: null
    default:
    - "$id.$key.read_1.fastq"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--qc_output2"
    description: "Path to output directory"
    info: null
    default:
    - "$id.$key.read_2.fastq"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fastqc_html_1"
    description: "FastQC HTML report for read 1."
    info: null
    default:
    - "$id.read_1.fastqc.html"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fastqc_html_2"
    description: "FastQC HTML report for read 2."
    info: null
    default:
    - "$id.read_2.fastqc.html"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fastqc_zip_1"
    description: "FastQC report archive for read 1."
    info: null
    default:
    - "$id.read_1.fastqc.zip"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fastqc_zip_2"
    description: "FastQC report archive for read 2."
    info: null
    default:
    - "$id.read_2.fastqc.zip"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--trim_log_1"
    info: null
    default:
    - "$id.read_1.trimming_report.txt"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--trim_log_2"
    info: null
    default:
    - "$id.read_2.trimming_report.txt"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--trim_html_1"
    info: null
    default:
    - "$id.read_1.trimmed_fastqc.html"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--trim_html_2"
    info: null
    default:
    - "$id.read_2.trimmed_fastqc.html"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--trim_zip_1"
    info: null
    default:
    - "$id.read_1.trimmed_fastqc.zip"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--trim_zip_2"
    info: null
    default:
    - "$id.read_2.trimmed_fastqc.zip"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--sortmerna_log"
    description: "Sortmerna log file."
    info: null
    default:
    - "$id.sortmerna.log"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--salmon_json_info"
    description: "File containing meta information from Salmon quant"
    info: null
    default:
    - "$id.salmon_meta_info.json"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--updated_versions"
    info: null
    default:
    - "versions.yml"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "nextflow_script"
  path: "main.nf"
  is_executable: true
  entrypoint: "run_wf"
description: "A subworkflow for the pre-processing stage of the nf-core/rnaseq pipeline.\n"
info: null
status: "enabled"
requirements:
  commands:
  - "ps"
dependencies:
- name: "fq_subsample"
  repository:
    type: "local"
- name: "salmon/salmon_quant"
  repository:
    type: "local"
- name: "fastqc"
  repository:
    type: "local"
- name: "umitools/umitools_extract"
  repository:
    type: "local"
- name: "trimgalore"
  repository:
    type: "local"
- name: "bbmap_bbsplit"
  repository:
    type: "local"
- name: "sortmerna"
  repository:
    type: "local"
- name: "fastp"
  repository:
    type: "vsh"
    repo: "viash-hub/biobase"
runners:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
engines:
- type: "native"
  id: "native"
build_info:
  config: "src/workflows/pre_processing/config.vsh.yaml"
  runner: "nextflow"
  engine: "native"
  output: "target/nextflow/workflows/pre_processing"
  executable: "target/nextflow/workflows/pre_processing/main.nf"
  viash_version: "0.9.0-RC2"
  git_commit: "f1bac79d3ebb4bff084f592da4371d1e3a1a6865"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh"
package_config:
  info: null
  viash_version: "0.9.0-RC2"
  source: "src"
  target: "target"
  config_mods:
  - ".version := 'dev'\n.requirements.commands := ['ps']\n.engines[.type == 'docker'].target_registry\
    \ := 'ghcr.io'\n.engines[.type == 'docker'].target_organization := 'data-intuitive'\n\
    .engines[.type == 'docker'].target_image_source := 'https://github.com/data-intuitive/rnaseq.vsh'\n\
    .runners[.type == 'nextflow'].directives.tag := '$id'\n.runners[.type == 'nextflow'].auto.simplifyOutput\
    \ := false"
  - ".version := \"main_build\""
