functionality:
  name: "star_genomegenerate"
  namespace: "star"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/nf-core/star/genomegenerate/main.nf, modules/nf-core/star/genomegenerate/meta.yml]
      last_sha: 92b2a7857de1dda9d1c19a088941fc81e2976ff7

  description: | 
    Create index for STAR

  arguments:
  - name: "--fasta"
    type: file
    description: Genome fasta file
  - name: "--gtf"
    type: file
    description: GTF file
  - name: "--versions"
    type: file
    must_exist: false
    

  - name: "--star_index"
    type: file
    direction: output
    description: STAR index directory.
    default: STAR_index
  - name: "--updated_versions"
    type: file
    default: versions.yml
    direction: output

  resources:
    - type: bash_script
      path: script.sh
  
  test_resources:
    - type: bash_script
      path: test.sh
    - path: /testData/minimal_test/reference/genes.gtf.gz
    - path: /testData/minimal_test/reference/genome.fasta
   
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: docker
        env: 
          - PACKAGES build-essential gcc g++ autoconf automake make wget zlib1g-dev unzip perl libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev bzip2 gawk
        run: |
          apt-get update && \
          apt-get install -y --no-install-recommends ${PACKAGES} && \
          wget --no-check-certificate https://github.com/samtools/samtools/releases/download/1.18/samtools-1.18.tar.bz2 && \
          tar -xjf samtools-1.18.tar.bz2 && \
          rm samtools-1.18.tar.bz2 && \
          cd samtools-1.18 && \
          ./configure && \
          make && \
          make install && \
          cd && \
          wget --no-check-certificate https://github.com/alexdobin/STAR/archive/refs/tags/2.7.11a.zip && \
          unzip 2.7.11a.zip && \
          cp STAR-2.7.11a/bin/Linux_x86_64_static/STAR /usr/local/bin 
          
  - type: nextflow
 