name: "umitools_extract"
namespace: "umitools"
version: "main_build"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "boolean"
    name: "--paired"
    description: "Paired fastq files or not?"
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input"
    description: "Input fastq files, either one or two (paired)"
    info: null
    example:
    - "sample.fastq"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "string"
    name: "--bc_pattern"
    description: "The UMI barcode pattern to use e.g. 'NNNNNN' indicates that the\
      \ first 6 nucleotides of the read are from the UMI."
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--versions"
    info: null
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fastq_1"
    description: "Output file for read 1."
    info: null
    default:
    - "$id.$key.read_1.fastq"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fastq_2"
    description: "Output file for read 2."
    info: null
    default:
    - "$id.$key.read_2.fastq"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--updated_versions"
    info: null
    default:
    - "versions.yml"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--umitools_extract_method"
    description: "UMI pattern to use."
    info: null
    default:
    - "string"
    required: false
    choices:
    - "string"
    - "regex"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--umitools_umi_separator"
    description: "The character that separates the UMI in the read name. Most likely\
      \ a colon if you skipped the extraction with UMI-tools and used other software."
    info: null
    default:
    - "_"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--umitools_grouping_method"
    description: "Method to use to determine read groups by subsuming those with similar\
      \ UMIs. All methods start by identifying the reads with the same mapping position,\
      \ but treat similar yet nonidentical UMIs differently."
    info: null
    default:
    - "directional"
    required: false
    choices:
    - "unique"
    - "percentile"
    - "cluster"
    - "adjacency"
    - "directional"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--umi_discard_read"
    description: "After UMI barcode extraction discard either R1 or R2 by setting\
      \ this parameter to 1 or 2, respectively."
    info: null
    default:
    - 0
    required: false
    choices:
    - 0
    - 1
    - 2
    direction: "input"
    multiple: false
    multiple_sep: ";"
resources:
- type: "bash_script"
  path: "script.sh"
  is_executable: true
description: "UMI-tools contains tools for dealing with Unique Molecular Identifiers\
  \ (UMIs)/Random Molecular Tags (RMTs) and single cell RNA-Seq cell barcodes. See\
  \ https://umi-tools.readthedocs.io/en/latest/ for more information.\nThis component\
  \ flexible removes UMI sequences from fastq reads. UMIs are removed and appended\
  \ to the read name.\nThis component extracts UMI barcode from a read and add it\
  \ to the read name, leaving any sample barcode in place\n"
test_resources:
- type: "bash_script"
  path: "test.sh"
  is_executable: true
- type: "file"
  path: "testData/unit_test_resources/scrb_seq_fastq.1.gz"
- type: "file"
  path: "testData/unit_test_resources/scrb_seq_fastq.2.gz"
- type: "file"
  path: "testData/unit_test_resources/slim.fastq.gz"
info:
  migration_info:
    git_repo: "https://github.com/nf-core/rnaseq.git"
    paths:
    - "modules/nf-core/umitools/extract/main.nf"
    - "modules/nf-core/umitools/extract/meta.yml"
    last_sha: "54721c6946daf6d602d7069dc127deef9cbe6b33"
status: "enabled"
requirements:
  commands:
  - "ps"
runners:
- type: "executable"
  id: "docker"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "ubuntu:22.04"
  target_organization: "data-intuitive"
  target_registry: "ghcr.io"
  target_tag: "main_build"
  namespace_separator: "/"
  target_image_source: "https://github.com/data-intuitive/rnaseq.vsh"
  setup:
  - type: "apt"
    packages:
    - "pip"
    interactive: false
  - type: "python"
    user: false
    packages:
    - "umi_tools"
    upgrade: true
  entrypoint: null
  cmd: null
build_info:
  config: "src/umitools/umitools_extract/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/umitools/umitools_extract"
  executable: "target/nextflow/umitools/umitools_extract/umitools_extract"
  viash_version: "0.9.0-RC2"
  git_commit: "f1bac79d3ebb4bff084f592da4371d1e3a1a6865"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh"
package_config:
  info: null
  viash_version: "0.9.0-RC2"
  source: "src"
  target: "target"
  config_mods:
  - ".version := 'dev'\n.requirements.commands := ['ps']\n.engines[.type == 'docker'].target_registry\
    \ := 'ghcr.io'\n.engines[.type == 'docker'].target_organization := 'data-intuitive'\n\
    .engines[.type == 'docker'].target_image_source := 'https://github.com/data-intuitive/rnaseq.vsh'\n\
    .runners[.type == 'nextflow'].directives.tag := '$id'\n.runners[.type == 'nextflow'].auto.simplifyOutput\
    \ := false"
  - ".version := \"main_build\""
  - ".engines[.type == 'docker'].target_tag := 'main_build'"
