functionality:
  name: salmon_quant_merge_counts
  namespace: workflows
  description: A sub-workflow to merge the counts obtained from salmon quant across all samples.

  arguments: 
    # Input
    - name: "--salmon_quant_results"
      type: file
    - name: "--gtf"
      type: file
    - name: "--gtf_extra_attributes"
      type: string
      default: 'gene_name'
    - name: "--gtf_group_features"
      type: string
      default: 'gene_id'

    # Output
    - name: "--tpm_gene"
      type: file
      direction: output
      default: salmon.merged.gene_tpm.tsv
    - name: "--counts_gene"
      type: file
      direction: output
      default: salmon.merged.gene_counts.tsv
    - name: "--counts_gene_length_scaled"
      type: file
      direction: output
      default: salmon.merged.gene_counts_length_scaled.tsv
    - name: "--counts_gene_scaled"
      type: file
      direction: output
      default: salmon.merged.gene_counts_scaled.tsv
    - name: "--tpm_transcript"
      type: file
      direction: output
      default: salmon.merged.transcript_tpm.tsv
    - name: "--counts_transcript"
      type: file
      direction: output
      default: salmon.merged.transcript_counts.tsv
    - name: "--salmon_merged_summarizedexperiment"
      type: file
      direction: output
      default: salmon_merged_summarizedexperiment

    # - name: "--pca_header_multiqc"
    #   type: file
    #   default: assets/multiqc/deseq2_pca_header.txt
    # - name: "--clustering_header_multiqc"
    #   type: file
    #   default: assets/multiqc/deseq2_clustering_header.txt
    # - name: "--deseq2_vst"
    #   type: boolean
    #   default: true
    #   description: Use vst transformation instead of rlog with DESeq2
    # - name: "--extra_deseq2_args"
    #   type: string
    #   default: "--id_col 1 --sample_suffix '' -outprefix deseq2 --count_col 3"
    # - name: "--extra_deseq2_args2"
    #   type: string
    #   default: star_salmon

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf

  dependencies: 
    - name: salmon/salmon_tx2gene
    - name: salmon/salmon_tximport
    - name: salmon/salmon_summarizedexperiment
    - name: deseq2_qc
    
platforms:
  - type: nextflow