functionality:
  name: "trimgalore"
  description: |
    A wrapper tool around Cutadapt and FastQC to consistently apply quality and adapter trimming to FastQ files. See https://www.bioinformatics.babraham.ac.uk/projects/trim_galore/ for more infomration.

  arguments:
    # Inputs
    - name: "--paired"
      type: boolean 
      required: false
      default: false
      description: Paired fastq files or not?
    - name: "--input"
      type: file
      required: true
      description: Input fastq files. 
      example: sample.fastq
      multiple: true
      multiple_sep: ","
    
    # Outputs
    # - name: "--output"
    #   alternatives: [ "-o" ]
    #   type: file
    #   required: true
    #   description: Output directory to write reports to.
    #   direction: output
    - name: "--fastq_1"
      type: file
      required: true
      description: Output file for read 1.
      direction: output
      default: $id.$key.read1.fq.gz
    - name: "--fastq_2"
      type: file
      required: false
      must_exist: false
      description: Output file for read 2.
      direction: output
      default: $id.$key.read2.fq.gz

    # Optional arguments
    - name: "--extra_trimgalore_args"
      type: string
      example: "--three_prime_clip_R1 15 --three_prime_clip_R2 15"
      description: "Extra arguments to pass to Trim Galore! command in addition to defaults defined by the pipeline."
      default: ""
    # - name: "--min_trimmed_reads"
    #   type: integer 
    #   description: "Minimum number of trimmed reads below which samples are removed from further processing. Some downstream steps in the pipeline will fail if this threshold is too low."
    #   default: 10000   
    
  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: apt
        packages: [fastqc]
      - type: apt
        packages: [cutadapt]
      - type: docker
        run: | 
          apt-get update && \
          apt-get install -y curl tar && \
          curl -fsSL https://github.com/FelixKrueger/TrimGalore/archive/0.6.10.tar.gz -o trim_galore.tar.gz && \
          tar -xvzf trim_galore.tar.gz && \
          cp /TrimGalore-0.6.10/trim_galore /usr/local/bin
  - type: nextflow

 
  
  
