functionality:
  name: "umitools_extract"
  namespace: "qc"
  description: |
    UMI-tools contains tools for dealing with Unique Molecular Identifiers (UMIs)/Random Molecular Tags (RMTs) and single cell RNA-Seq cell barcodes. See https://umi-tools.readthedocs.io/en/latest/ for more information.
    This component flexible removes UMI sequences from fastq reads. UMIs are removed and appended to the read name.
  arguments:
    # Inputs
    - name: "--paired"
      type: boolean 
      required: false
      default: false
      description: Paired fastq files or not?
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      multiple: true
      multiple_sep: ","
      description: Input fastq files, either one or two (paired)
      example: sample.fastq
    - name: "--bc_pattern"
      type: string
      description: "The UMI barcode pattern to use e.g. 'NNNNNN' indicates that the first 6 nucleotides of the read are from the UMI."
      multiple: true
      multiple_sep: ","
    
    # Outputs
    - name: "--output_1"
      type: file
      required: true
      description: Output file for read 1.
      direction: output
    - name: "--output_2"
      type: file
      required: false
      description: Output file for read 2.
      direction: output

    # Optional arguments
    - name: "--umitools_extract_method"
      type: "string"
      description: UMI pattern to use.
      default: string
      choices: [ string, regex ]
    - name: "--umitools_umi_separator"
      type: string
      default: "_"
      description: The character that separates the UMI in the read name. Most likely a colon if you skipped the extraction with UMI-tools and used other software.
    # - name: "--umitools_grouping_method"
    #   type: string
    #   description: Method to use to determine read groups by subsuming those with similar UMIs. All methods start by identifying the reads with the same mapping position, but treat similar yet nonidentical UMIs differently.
    #   default: "directional"
    #   choices: ["unique", "percentile", "cluster", "adjacency", "directional"]
    # - name: "--umi_discard_read"
    #   type: integer
    #   description: After UMI barcode extraction discard either R1 or R2 by setting this parameter to 1 or 2, respectively.
    #   choices: [1, 2]
    - name: "--save_umi_intermeds"
      type: boolean
      description: If this option is specified, intermediate FastQ and BAM files produced by UMI-tools are also saved in the results directory.
      default: false

  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: apt
        packages: [pip]
      - type: python
        packages: [umi-tools]
  - type: nextflow

 
  
  
