functionality:
  name: "gtf_gene_filter"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/local/gtf_gene_filter.nf]
      last_sha: 0a1bdcfbb498987643b74e9fccab85ccd9f2a17d
  description: | 
    Filter GTF only for features in the genome

  arguments:
  - name: "--fasta"
    type: file
    description: Genome fasta file
  - name: "--gtf"
    type: file
    description: GTF file
  - name: "--versions"
    type: file
    must_exist: false
    

  - name: "--filtered_gtf"
    type: file
    direction: output
    description: Filtered GTF file containing only genes in the genome
  - name: "--updated_versions"
    type: file
    default: versions.yml
    direction: output

  resources:
    - type: bash_script
      path: script.sh
    # copied from https://github.com/nf-core/rnaseq/blob/master/bin/filter_gtf_for_genes_in_genome.py
    - path: filter_gtf_for_genes_in_genome.py
  
  test_resources:
    - type: bash_script
      path: test.sh
    - path: /testData/reference/genome.fasta
    - path: /testData/reference/genes.gtf.gz
   
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: apt
        packages: [pip]
      - type: python
  - type: nextflow