functionality:
  name: "cat_additional_fasta"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/local/cat_additional_fasta.nf]
      last_sha: 0a1bdcfbb498987643b74e9fccab85ccd9f2a17d
  description: |
    Concatenate addional fasta file to reference FASTA and GTF files.

  arguments:
    - name: "--fasta"
      type: file 
      required: true
      description: Path to FASTA genome file.
    - name: "--gtf"
      type: file
      description: Path to GTF annotation file.
    - name: "--additional_fasta"
      type: file
      description: FASTA file to concatenate to genome FASTA file e.g. containing spike-in sequences.
    - name: "--biotype"
      type: string
      description: Biotype value to use when appending entries to GTF file when additional fasta file is provided.
    - name: "--versions"
      type: file
      must_exist: false

    # Output
    - name: "--fasta_output"
      type: file
      direction: output
      description: Concatenated FASTA file.
    - name: "--gtf_output"
      type: file
      direction: output
      description: Concatenated GTF file.
    - name: "--updated_versions"
      type: file
      default: versions.yml
      direction: output
  
  resources:
    - type: bash_script
      path: script.sh
    # copied from https://github.com/nf-core/rnaseq/blob/master/bin/fasta2gtf.py
    - path: fasta2gtf.py
  
  test_resources:
    - type: bash_script
      path: test.sh
    - path: /testData/reference/genome.fasta
    - path: /testData/reference/genes.gtf.gz
    - path: /testData/reference/gfp.fa.gz
   
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: apt
        packages: [pip]
      - type: python
  - type: nextflow