functionality:
  name: quality_control
  namespace: workflows
  description: |
    A subworkflow for the pre-processing stage of the nf-core/rnaseq pipeline.
  argument_groups:
    - name: Input
      arguments:
        - name: "--id"
          required: true
          description: ID of the sample
          type: string 
          example: test

        - name: "--bam_input"
          required: true
          type: file
          description: Path to input alignment file in BAM or SAM format.
          example: sample.bam

        - name: "--bai_input"
          required: true
          type: file
          description: Path to bam index file in bai format.
          example: sample.bai

        - name: "--gtf_input"
          required: true
          type: file
          description: Path to gtf annotation file (gz zipped format).
          example: genes.gtf.gz

        - name: "--refgene"
          type: file 
          required: true
          description: path to reference gene model in bed format

        - name: "--paired"
          type: boolean_true
          description: Setting this flag indicates a paired-end experiment.

        - name: "--strandedness"
          type: string
          required: false
          choices: ["forward", "reverse"]
          description: strandedness of input bam file reads (forward, reverse or null (default, applicable to paired reads))

        - name: "--sample_size"
          type: integer
          required: false
          default: 200000
          min: 1
          description: Numer of reads sampled from SAM/BAM file to infer experiment and calculate inner distance, default = 200000.

        - name: "--lower_bound_size"
          type: integer
          required: false
          default: -250 
          description: Lower bound of inner distance (bp). This option is used for ploting histograme, default=-250.

        - name: "--upper_bound_size"
          type: integer
          required: false
          default: 250 
          description: Upper bound of inner distance (bp). This option is used for ploting histograme, default=250.

        - name: "--step_size"
          type: integer
          required: false
          default: 5 
          description: Step size (bp) of histograme of inner distance. This option is used for plotting histogram, default=5.        

        - name: "--map_qual"
          type: integer
          required: false
          default: 30 
          description: Minimum mapping quality (phred scaled) to determine uniquely mapped reads, default=30.
          min: 0

        - name: "--min_intron"
          type: integer
          required: false
          default: 50
          min: 1 
          description: Minimum intron length (bp) to call a junction, default = 50.

        - name: "--min_splice_read"
          type: integer
          required: false
          default: 1
          min: 1 
          description: Minimum number of supporting reads to call a junction, default = 1.

        - name: "--sampling_percentile_lower_bound"
          type: integer
          required: false
          default: 5 
          description: Read sampling for junction saturation starts from this percentile, must be an integer between 0 and 100, default =5.
          min: 0
          max: 100

        - name: "--sampling_percentile_upper_bound"
          type: integer
          required: false
          default: 100
          description: Read sampling for junction saturation ends at this percentile, must be an integer between 0 and 100, default =5.
          min: 0
          max: 100
      
        - name: "--sampling_percentile_step"
          type: integer
          required: false
          default: 5
          description: Read sampling for junction saturation frequency in %. Smaller value means more sampling times. Must be an integer between 0 and 100, default = 5.
          min: 0
          max: 100

        - name: "--read_count_upper_limit"
          type: integer
          required: false
          default: 500
          description: Upper limit of reads' occurence to determine read duplication. Only used for plotting, default = 500 (times).
          min: 1 

        - name: "--minimum_coverage"
          type: integer
          required: false
          default: 10
          min: 1
          description: Minimum number of reads mapped to a transcript to determin tin, default = 10.

        - name: "--tin_sample_size"
          type: integer
          required: false
          default: 100
          min: 1
          description: Number of equal-spaced nucleotide positions picked from mRNA. Note, if this number is larger than the length of mRNA (L), it will be halved until it's smaller than L (default = 100)

        - name: "--subtract_background"
          type: boolean_true
          description: Set flag to subtract background noise (estimated from intronic reads) to determine tin. Only use this option if there are substantial intronic reads.
          
        - name: "--output_format"
          type: string
          required: false
          default: html
          description: Format of the qualimap output report (PDF or HTML, default is HTML)

        - name: "--pr_bases"
          type: integer
          required: false
          default: 100
          min: 1
          description: Number of upstream/downstream nucleotide bases to compute 5'-3' bias for qualimap (default = 100).
    
        - name: "--tr_bias"
          type: integer
          required: false
          default: 1000
          min: 1
          description: Number of top highly expressed transcripts to compute 5'-3' bias for qualimap (default = 1000).

        - name: "--algorithm"
          type: string
          required: false
          default: uniquely-mapped-reads
          description: Counting algorithm for qualimap (uniquely-mapped-reads (default) or proportional).

        - name: "--sequencing_protocol"
          type: string
          required: false
          choices: ["non-strand-specific", "strand-specific-reverse", "strand-specific-forward"]
          default: non-strand-specific
          description: Sequencing library protocol for qualimap (strand-specific-forward, strand-specific-reverse or non-strand-specific (default)).

        - name: "--sorted"
          type: boolean_true
          description: Setting this flag indicates that the input file is already sorted by name. If flag is not set, additional sorting by name will be performed for qualimap. Only requiredfor paired-end analysis.

        - name: "--java_memory_size"
          type: string
          required: false
          default: 4G 
          description: maximum Java heap memory size for qualimap, default = 4G.
          
    - name: Output
      arguments:
        - name: "--bamstat_output"
          type: file
          direction: output
          required: false
          description: Path to output file (txt) of mapping quality statistics
          default: mapping_quality.txt

        - name: "--strandedness_output"
          type: file
          direction: output
          required: false
          default: strandedness.txt
          description: Path to output report (txt) of inferred strandedness

        - name: "--inner_dist_output_stats"
          type: file
          direction: output
          required: false
          must_exist: false
          default: inner_distance_stats.txt
          description: output file (txt) with summary statistics of inner distances of paired reads

        - name: "--inner_dist_output_dist"
          type: file
          direction: output
          required: false
          must_exist: false
          default: inner_distance.txt
          description: output file (txt) with inner distances of all paired reads

        - name: "--inner_dist_output_freq"
          type: file
          direction: output
          required: false
          must_exist: false
          default: inner_distance_freq.txt
          description: output file (txt) with frequencies of inner distances of all paired reads

        - name: "--inner_dist_output_plot"
          type: file
          direction: output
          required: false
          must_exist: false
          default: inner_distance_plot.pdf
          description: output file (pdf) with histogram plot of of inner distances of all paired reads

        - name: "--inner_dist_output_plot_r"
          type: file
          direction: output
          required: false
          must_exist: false
          default: inner_distance_plot.r
          description: output file (R) with script of histogram plot of of inner distances of all paired reads

        - name: "--junction_annotation_output_log"
          type: file
          direction: output
          required: false
          default: junction_annotation.log
          description: output log of junction annotation script

        - name: "--junction_annotation_output_plot_r"
          type: file
          direction: output
          required: false
          default: junction_annotation_plot.r
          description: r script to generate splice_junction and splice_events plot

        - name: "--junction_annotation_output_junction_bed"
          type: file
          direction: output
          required: false
          default: junction_annotation.bed
          description: junction annotation file (bed format)

        - name: "--junction_annotation_output_junction_interact"
          type: file
          direction: output
          required: false
          default: junction_annotation.Interact.bed
          description: interact file (bed format) of junctions. Can be uploaded to UCSC genome browser or converted to bigInteract (using bedToBigBed program) for visualization.

        - name: "--junction_annotation_output_junction_sheet"
          type: file
          direction: output
          required: false
          default: junction_annotation.xls
          description: junction annotation file (xls format)

        - name: "--junction_annotation_output_splice_events_plot"
          type: file
          direction: output
          required: false
          default: splice_events.pdf
          description: plot of splice events (pdf)

        - name: "--junction_annotation_output_splice_junctions_plot"
          type: file
          direction: output
          required: false
          default: splice_junctions_plot.pdf
          description: plot of junctions (pdf)

        - name: "--junction_saturation_output_plot_r"
          type: file
          direction: output
          required: false
          default: junction_saturation_plot.r
          description: r script to generate junction_saturation_plot plot

        - name: "--junction_saturation_output_plot"
          type: file
          direction: output
          required: false
          default: junction_saturation_plot.pdf
          description: plot of junction saturation (pdf)

        - name: "--read_distribution_output"
          type: file
          direction: output
          required: false
          default: read_distribution.txt
          description: output file (txt) of read distribution analysis.
    
        - name: "--read_duplication_output_duplication_rate_plot_r"
          type: file
          direction: output
          required: false
          default: duplication_rate_plot.r
          description: R script for generating duplication rate plot

        - name: "--read_duplication_output_duplication_rate_plot"
          type: file
          direction: output
          required: false
          default: duplication_rate_plot.pdf
          description: duplication rate plot (pdf)

        - name: "--read_duplication_output_duplication_rate_mapping"
          type: file
          direction: output
          required: false
          default: duplication_rate_mapping.xls
          description: Summary of mapping-based read duplication

        - name: "--read_duplication_output_duplication_rate_sequence"
          type: file
          direction: output
          required: false
          default: duplication_rate_sequencing.xls
          description: Summary of sequencing-based read duplication

        - name: "--tin_output_summary"
          type: file
          direction: output
          required: false
          default: tin_summary.txt
          description: summary statistics (txt) of calculated TIN metrics

        - name: "--tin_output_metrics"
          type: file
          direction: output
          required: false
          default: tin.xls
          description: file with TIN metrics (xls)

        - name: "--dupradar_output_dupmatrix"
          type: file
          direction: output
          required: false
          default: dup_matrix.txt
          description: path to output file (txt) of duplicate tag counts
      
        - name: "--dupradar_output_dup_intercept_mqc"
          type: file
          direction: output
          required: false
          default: dup_intercept_mqc.txt
          description: path to output file (txt) of multiqc intercept value DupRadar
    
        - name: "--dupradar_output_duprate_exp_boxplot"
          type: file
          direction: output
          required: false
          default: duprate_exp_boxplot.pdf
          description: path to output file (pdf) of distribution of expression box plot
      
        - name: "--dupradar_output_duprate_exp_densplot"
          type: file
          direction: output
          required: false
          default: duprate_exp_densityplot.pdf
          description: path to output file (pdf) of 2D density scatter plot of duplicate tag counts
      
        - name: "--dupradar_output_duprate_exp_denscurve_mqc"
          type: file
          direction: output
          required: false
          default: duprate_exp_density_curve_mqc.pdf
          description: path to output file (pdf) of density curve of gene duplication multiqc
      
        - name: "--dupradar_output_expression_histogram"
          type: file
          direction: output
          required: false
          default: expression_hist.pdf
          description: path to output file (pdf) of distribution of RPK values per gene histogram
        
        - name: "--dupradar_output_intercept_slope"
          type: file
          direction: output
          required: false
          default: intercept_slope.txt

        - name: "--qualimap_output_pdf"
          type: file
          direction: output
          required: false
          must_exist: false
          default: qualimap_output.pdf

        - name: "--qualimap_output_dir"
          type: file
          direction: output
          required: false
          default: $id_qualimap_output

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf

  dependencies:
    - name: rseqc/rseqc_bamstat
    - name: rseqc/rseqc_inferexperiment
    - name: rseqc/rseqc_innerdistance
    - name: rseqc/rseqc_junctionannotation
    - name: rseqc/rseqc_junctionsaturation
    - name: rseqc/rseqc_readdistribution
    - name: rseqc/rseqc_readduplication
    - name: rseqc/rseqc_tin
    - name: dupradar
    - name: qualimap

platforms:
  - type: nextflow