functionality:
  name: quality_control
  namespace: workflows
  description: |
    A subworkflow for the pre-processing stage of the nf-core/rnaseq pipeline.
  argument_groups:
    - name: Input
      arguments:
        - name: "--id"
          required: true
          description: ID of the sample
          type: string 
          example: test

        - name: "--bam_input"
          required: true
          type: file
          required: true
          description: Path to input alignment file in BAM or SAM format.
          example: sample.bam

        - name: "--refgene"
          type: file 
          required: true
          description: path to reference gene model in bed format

        - name: "--paired"
          type: boolean_true
          description: Setting this flag indicates a paired-end experiment.

        - name: "--sample_size"
          type: integer
          required: false
          default: 200000
          min: 1
          description: Numer of reads sampled from SAM/BAM file to infer experiment and calculate inner distance, default = 200000.

        - name: "--lower_bound_size"
          type: integer
          required: false
          default: -250 
          description: Lower bound of inner distance (bp). This option is used for ploting histograme, default=-250.

        - name: "--upper_bound_size"
          type: integer
          required: false
          default: 250 
          description: Upper bound of inner distance (bp). This option is used for ploting histograme, default=250.

        - name: "--step_size"
          type: integer
          required: false
          default: 5 
          description: Step size (bp) of histograme of inner distance. This option is used for plotting histogram, default=5.        

        - name: "--map_qual"
          type: integer
          required: false
          default: 30 
          description: Minimum mapping quality (phred scaled) to determine uniquely mapped reads, default=30.
          min: 0

    - name: Output
      arguments:
        - name: "--bamstat_output"
          type: file
          direction: output
          required: false
          description: Path to output file (txt) of mapping quality statistics
          default: mapping_quality.txt

        - name: "--strandedness_output"
          type: file
          direction: output
          required: false
          default: strandedness.txt
          description: Path to output report (txt) of inferred strandedness

        - name: "--inner_dist_output_stats"
          type: file
          direction: output
          required: false
          must_exist: false
          default: inner_distance_stats.txt
          description: output file (txt) with summary statistics of inner distances of paired reads

        - name: "--inner_dist_output_dist"
          type: file
          direction: output
          required: false
          must_exist: false
          default: inner_distance.txt
          description: output file (txt) with inner distances of all paired reads

        - name: "--inner_dist_output_freq"
          type: file
          direction: output
          required: false
          must_exist: false
          default: inner_distance_freq.txt
          description: output file (txt) with frequencies of inner distances of all paired reads

        - name: "--inner_dist_output_plot"
          type: file
          direction: output
          required: false
          must_exist: false
          default: inner_distance_plot.pdf
          description: output file (pdf) with histogram plot of of inner distances of all paired reads

        - name: "--inner_dist_output_plot_r"
          type: file
          direction: output
          required: false
          must_exist: false
          default: inner_distance_plot.r
          description: output file (R) with script of histogram plot of of inner distances of all paired reads


  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf

  dependencies:
    - name: rseqc/rseqc_bamstat
    - name: rseqc/rseqc_inferexperiment
    - name: rseqc/rseqc_innerdistance

platforms:
  - type: nextflow