name: "prepare_multiqc_input"
version: "main_build"
argument_groups:
- name: "Input"
  arguments:
  - type: "string"
    name: "--fail_trimming_multiqc"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--fail_mapping_multiqc"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--fail_strand_multiqc"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fastqc_raw_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--fastqc_trim_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--trim_log_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--sortmerna_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--star_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--salmon_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--samtools_stats"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--samtools_flagstat"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--samtools_idxstats"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--markduplicates_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--featurecounts_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--featurecounts_rrna_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--aligner_pca_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--aligner_clustering_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--preseq_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--qualimap_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--dupradar_output_dup_intercept_mqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--dupradar_output_duprate_exp_denscurve_mqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--bamstat_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--inferexperiment_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--innerdistance_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--junctionannotation_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--junctionsaturation_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--readdistribution_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--readduplication_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--tin_multiqc"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
- name: "Ouput"
  arguments:
  - type: "file"
    name: "--output"
    info: null
    default:
    - "multiqc_input"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "bash_script"
  path: "script.sh"
  is_executable: true
description: "Prepare directory with all the input files for MultiQC.\n"
info: null
status: "enabled"
requirements:
  commands:
  - "ps"
runners:
- type: "executable"
  id: "docker"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "ubuntu:22.04"
  target_organization: "data-intuitive"
  target_registry: "ghcr.io"
  target_tag: "main_build"
  namespace_separator: "/"
  target_image_source: "https://github.com/data-intuitive/rnaseq.vsh"
  entrypoint: null
  cmd: null
build_info:
  config: "src/prepare_multiqc_input/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/prepare_multiqc_input"
  executable: "target/nextflow/prepare_multiqc_input/prepare_multiqc_input"
  viash_version: "0.9.0-RC2"
  git_commit: "f1bac79d3ebb4bff084f592da4371d1e3a1a6865"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh"
package_config:
  info: null
  viash_version: "0.9.0-RC2"
  source: "src"
  target: "target"
  config_mods:
  - ".version := 'dev'\n.requirements.commands := ['ps']\n.engines[.type == 'docker'].target_registry\
    \ := 'ghcr.io'\n.engines[.type == 'docker'].target_organization := 'data-intuitive'\n\
    .engines[.type == 'docker'].target_image_source := 'https://github.com/data-intuitive/rnaseq.vsh'\n\
    .runners[.type == 'nextflow'].directives.tag := '$id'\n.runners[.type == 'nextflow'].auto.simplifyOutput\
    \ := false"
  - ".version := \"main_build\""
  - ".engines[.type == 'docker'].target_tag := 'main_build'"
