functionality:
  name: "rseqc_readdistribution"
  namespace: "rseqc"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/nf-core/rseqc/readdistribution/main.nf]
      last_sha: 
  description: |
    Calculate how mapped reads are distributed over genomic features.

  arguments:
    - name: "--input"
      type: file 
      required: true
      description: input alignment file in BAM or SAM format

    - name: "--refgene"
      type: file 
      required: true
      description: Reference gene model in bed format
    
    - name: "--versions"
      type: file
      must_exist: false
      
   
    - name: "--output"
      type: file
      direction: output
      required: false
      default: $id.read_distribution.txt
      description: output file (txt) of read distribution analysis.

    - name: "--updated_versions"
      type: file
      default: versions.yml
      direction: output

  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
    - path: /testData/unit_test_resources/Pairend_StrandSpecific_51mer_Human_hg19.bam
    - path: /testData/unit_test_resources/hg19_RefSeq.bed.gz  
   
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:   
      - type: apt
        packages: [ python3-pip ]
      - type: python
        packages: [ RSeQC ]
  - type: nextflow