functionality:
  name: "preseq_lcextrap"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/nf-core/preseq/lcextrap/main.nf, modules/nf-core/preseq/lcextrap/meta.yml]
      last_sha: 54721c6946daf6d602d7069dc127deef9cbe6b33
  description: Predicting library complexity and genome coverage in high-throughput sequencing

  arguments: 
    - name: "--bam"
      type: file
      description: Input genome BAM file
    - name: "--bed"
      type: file
      description: Input bed file
    - name: "--extra_preseq_args"
      type: string
    - name: "--paired"
      type: boolean
      description: Paired-end reads?

    - name: "--output"
      type: file
      direction: output
      default: $id.lc_extrap.txt

  resources:
    - type: bash_script
      path: script.sh

platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: apt
        packages: [ curl, bzip2, build-essential, wget, gcc, autoconf, automake, make, libz-dev, libbz2-dev, zlib1g-dev, libncurses5-dev, libncursesw5-dev, liblzma-dev, pip ]
      - type: docker
        run: | 
          cd /usr/bin && \
          wget --no-check-certificate https://github.com/smithlabcode/preseq/releases/download/v3.1.2/preseq-3.1.2.tar.gz && \
          wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2 && \
          wget --no-check-certificate https://github.com/arq5x/bedtools2/releases/download/v2.31.0/bedtools.static && \
          curl -fsSL https://github.com/samtools/samtools/releases/download/1.18/samtools-1.18.tar.bz2 -o samtools-1.18.tar.bz2 && \
          tar -xjf samtools-1.18.tar.bz2 && rm samtools-1.18.tar.bz2 && \
          tar -xzf preseq-3.1.2.tar.gz && rm preseq-3.1.2.tar.gz && \
          tar -vxjf htslib-1.9.tar.bz2 && rm htslib-1.9.tar.bz2 && \
          mv bedtools.static /usr/local/bin/bedtools && \
          chmod a+x /usr/local/bin/bedtools && \
          cd samtools-1.18 && \
          ./configure && \
          make && \
          make install && \
          cd /usr/bin && cd htslib-1.9 && \
          make && \
          cd /usr/bin && cd preseq-3.1.2 && \
          mkdir build && cd build && \
          ../configure && \
          make && make install && make HAVE_HTSLIB=1 all 
  - type: nextflow
  