name: "preseq_lcextrap"
info:
  migration_info:
    git_repo: https://github.com/nf-core/rnaseq.git
    paths: [modules/nf-core/preseq/lcextrap/main.nf, modules/nf-core/preseq/lcextrap/meta.yml]
    last_sha: 54721c6946daf6d602d7069dc127deef9cbe6b33
description: Computing the expected future yield of distinct reads and bounds on the number of total distinct reads in the library and the associated confidence intervals.

argument_groups:
- name: "Input"
  arguments: 
  - name: "--input"
    type: file
    description: Input genome BAM/BED file
  - name: "--extra_preseq_args"
    type: string
  - name: "--paired"
    type: boolean
    description: Paired-end reads?
    
- name: "Output"
  arguments:
  - name: "--output"
    type: file
    direction: output
    default: $id.lc_extrap.txt

resources:
  - type: bash_script
    path: script.sh

test_resources:
  - type: bash_script
    path: test.sh
  - path: /testData/unit_test_resources/a.sorted.bed
  - path: /testData/unit_test_resources/SRR1106616_5M_subset.bam

engines:
- type: docker
  image: ubuntu:22.04
  setup:
    - type: apt
      packages: [ curl, bzip2, build-essential, wget, gcc, autoconf, automake, make, libz-dev, libbz2-dev, zlib1g-dev, libncurses5-dev, libncursesw5-dev, liblzma-dev, pip ]
    - type: docker
      run: | 
        cd /usr/bin && \
        wget --no-check-certificate https://github.com/smithlabcode/preseq/releases/download/v3.2.0/preseq-3.2.0.tar.gz && \
        wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2 && \
        wget --no-check-certificate https://github.com/arq5x/bedtools2/releases/download/v2.31.0/bedtools.static && \
        curl -fsSL https://github.com/samtools/samtools/releases/download/1.18/samtools-1.18.tar.bz2 -o samtools-1.18.tar.bz2 && \
        tar -xjf samtools-1.18.tar.bz2 && rm samtools-1.18.tar.bz2 && \
        tar -xzf preseq-3.2.0.tar.gz && rm preseq-3.2.0.tar.gz && \
        tar -vxjf htslib-1.9.tar.bz2 && rm htslib-1.9.tar.bz2 && \
        mv bedtools.static /usr/local/bin/bedtools && \
        chmod a+x /usr/local/bin/bedtools && \
        cd samtools-1.18 && \
        ./configure && \
        make && \
        make install && \
        cd /usr/bin && cd htslib-1.9 && \
        make && \
        cd /usr/bin && cd preseq-3.2.0 && \
        mkdir build && cd build && \
        ../configure && \
        make && make install && make HAVE_HTSLIB=1 all 
runners:
- type: executable
- type: nextflow
