functionality:
  name: "multiqc_custom_biotype"
  info: 
    migration_info: 
  description: Calculate features percentage for biotype counts

  arguments: 
  - name: "--biocounts"
    type: file
    description: File with all biocounts
  - name: "--id"
    type: string
    description: Sample name
    default: $id
  - name: "--biotypes_header"
    type: file
    default: assets/multiqc/biotypes_header.txt


  - name: '--featurecounts_multiqc'
    type: file
    direction: output
    default: $id.biotype_counts_rrna_mqc.tsv
  
  resources:
    - type: bash_script
      path: script.sh
    # Copied from https://github.com/nf-core/rnaseq/blob/3.12.0/bin/mqc_features_stat.py
    - path: mqc_features_stat.py

  test_resources:
    - type: bash_script
      path: test.sh
    # - path: /feature_counts_output/

platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: apt
        packages: [pip]
      - type: python
  - type: nextflow