name: "multiqc_custom_biotype"
info: 
  migration_info: 
description: Calculate features percentage for biotype counts

argument_groups: 
- name: "Input"
  arguments:
  - name: "--biocounts"
    type: file
    description: File with all biocounts
  - name: "--id"
    type: string
    description: Sample name
    default: $id
  - name: "--features"
    type: string
    description: Features to count
    default: rRNA
  
- name: "Output"
  arguments:
  - name: '--featurecounts_multiqc'
    type: file
    direction: output
    default: $id.biotype_counts_mqc.tsv
  - name: '--featurecounts_rrna_multiqc'
    type: file
    direction: output
    default: $id.biotype_counts_rrna_mqc.tsv

resources:
  # Adapted from https://github.com/nf-core/rnaseq/blob/3.12.0/bin/mqc_features_stat.py
  - type: python_script
    path: script.py
  # Include the header for the biotypes in the component
  - path: biotypes_header.txt

engines:
  - type: docker
    image: python:latest
runners: 
  - type: executable
  - type: nextflow
