name: "gtf2bed"
info:
  migration_info:
    git_repo: https://github.com/nf-core/rnaseq.git
    paths: [modules/local/gtf2bed.nf]
    last_sha: 0a1bdcfbb498987643b74e9fccab85ccd9f2a17d
description: |
  Create BED annotation file from GTF.

argument_groups:
- name: "Input"
  arguments:
  - name: "--gtf"
    type: file 
    required: true
    description: A reference file in GTF format.
    
- name: " Output"
  arguments:  
  - name: "--bed_output"
    type: file
    direction: output
    required: true
    description: BED file resulting from the conversion of the GTF input file.

resources:
  - type: bash_script
    path: script.sh
  # Copied from https://github.com/nf-core/rnaseq/blob/3.12.0/bin/gtf2bed
  - path: gtf2bed.pl

test_resources:
  - type: bash_script
    path: test.sh
  - path: /testData/minimal_test/reference/genes.gtf.gz
  
engines:
  - type: docker
    image: ubuntu:22.04
    setup:  
      - type: apt
        packages: [perl]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midmem, midcpu ]
