functionality:
  name: "gtf2bed"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/local/gtf2bed.nf]
      last_sha: 0a1bdcfbb498987643b74e9fccab85ccd9f2a17d
  description: |
    Create BED annotation file from GTF.

  arguments:
    - name: "--gtf"
      type: file 
      required: true
      description: A reference file in GTF format.
    
    - name: "--bed_output"
      type: file
      direction: output
      required: true
      description: BED file resulting from the conversion of the GTF input file.

  resources:
    - type: bash_script
      path: script.sh
    # Copied from https://github.com/nf-core/rnaseq/blob/3.12.0/bin/gtf2bed
    - path: gtf2bed.pl
  
  test_resources:
    - type: bash_script
      path: test.sh
    - path: /testData/reference/genes.gtf.gz
   
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:  
      - type: apt
        packages: [perl]
  - type: nextflow
