functionality:
  name: "gtf2bed"
  description: |
    Create BED annotation file from GTF.

  arguments:
    - name: "--gtf"
      type: file 
      required: true
      description: A reference file in GTF format.
    
    - name: "--bed_output"
      type: file
      direction: output
      required: true
      description: BED file resulting from the conversion of the GTF input file.

  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
   
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:   
      - type: docker
        run: | 
          apt-get update && \
          apt-get install -y wget tar bzip2 && \
          wget https://github.com/bedops/bedops/releases/download/v2.4.41/bedops_linux_x86_64-v2.4.41.tar.bz2 && \
          tar jxvf bedops_linux_x86_64-v2.4.41.tar.bz2 && \
          cp bin/* /usr/local/bin
  - type: nextflow
