functionality:
  name: "rseqc_tin"
  namespace: "rseqc"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/nf-core/rseqc/tin/main.nf]
      last_sha: 
  description: |
    Calculte TIN (transcript integrity number) from RNA-seq reads

  arguments:
    - name: "--input"
      type: file 
      required: true
      description: bam file to calculate statistics of, bai file of must be in the same directory.
 
    - name: "--refgene"
      type: file 
      required: true
      description: BED file containing the reference gene model

    - name: "--minimum_coverage"
      type: integer
      required: false
      default: 10
      min: 1
      description: Minimum number of reads mapped to a transcript, default = 10.

    - name: "--subtract_backtround"
      type: boolean
      required: false
      default: false
      description: Subtract background noise (estimated from intronic reads). Only use this option if there are substantial intronic reads, default = false.

    - name: "--output_tin_summary"
      type: file
      direction: output
      required: false
      default: tin_summary.txt
      description: summary statistics (txt) of calculated TIN metrics

    - name: "--output_tin"
      type: file
      direction: output
      required: false
      default: tin.xls
      description: file with TIN metrics (xls)

  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
   
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:   
      - type: "apt"
        packages: [python3-pip]
      - type: docker
        run: | 
          pip3 install RSeQC
  - type: nextflow