name: "untar"
info:
  migration_info:
    git_repo: https://github.com/nf-core/rnaseq.git
    paths: [modules/nf-core/untar/main.nf, modules/nf-core/untar/meta.yml]
    last_sha: 54721c6946daf6d602d7069dc127deef9cbe6b33
description: |
  Extract tar.gz files.

argument_groups:
- name: "Input"
  arguments:
  - name: "--input"
    type: file 
    description: Path of file to be uncompressed
    
- name: "Output"
  arguments:  
  - name: "--output"
    type: file
    direction: output
    description: Directory containing contents of uncompressed file.

resources:
  - type: bash_script
    path: script.sh

test_resources:
  - type: bash_script
    path: test.sh
  - path: /testData/minimal_test/reference/hisat2.tar.gz
  
engines:
- type: docker
  image: ubuntu:22.04
  setup:
    - type: apt
      packages: [ tar ]
runners: 
- type: executable
- type: nextflow
