functionality:
  name: "salmon_quant"
  namespace: "salmon"
  version: "dev"
  arguments:
  - type: "boolean"
    name: "--paired"
    description: "Paired-end reads or not?"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--strandedness"
    description: "Sample strand-specificity. Must be one of unstranded, forward, reverse\
      \ or auto"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--input"
    description: "List of input FastQ files of size 1 and 2 for single-end and paired-end\
      \ data, respectively."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
    dest: "par"
  - type: "file"
    name: "--salmon_index"
    description: "Folder containing the salmon index files"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--gtf"
    description: "GTF of the reference transcriptome"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--transcript_fasta"
    description: "Fasta file of the reference transcriptome"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--alignment_mode"
    description: "whether to run salmon in alignment mode"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--lib_type"
    description: "Override library type inferred based on strandedness defined in\
      \ meta object"
    info: null
    default:
    - ""
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--extra_salmon_quant_args"
    description: "Extra arguments to pass to salmon quant command in addition to defaults\
      \ defined by the pipeline."
    info: null
    default:
    - ""
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    description: "Folder containing the quantification results for a specific sample"
    info: null
    default:
    - "$id.salmon_quant"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--json_info"
    description: "File containing meta information from Salmon quant"
    info: null
    default:
    - "$id.$key.meta_info.json"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Gene/transcript quantification with Salmon.\n"
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  info:
    migration_info:
      git_repo: "https://github.com/nf-core/rnaseq.git"
      paths:
      - "modules/nf-core/salmon/quant/main.nf"
      - "modules/nf-core/salmon/quant/meta.yml"
      last_sha: "54721c6946daf6d602d7069dc127deef9cbe6b33"
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ubuntu:18.04"
  target_organization: "data-intuitive"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/data-intuitive/rnaseq.vsh"
  setup:
  - type: "docker"
    run:
    - "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone\
      \ && \\\napt-get update && \\\napt remove -y libcurl4 && \\\napt-get install\
      \ -y --no-install-recommends ${PACKAGES} && \\\napt-get clean && \\\nwget -O\
      \ - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key\
      \ add - && \\\napt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic\
      \ main' && \\\napt-get update && \\\napt-key --keyring /etc/apt/trusted.gpg\
      \ del C1F34CDD40CD72DA && \\\napt-get install kitware-archive-keyring && \\\n\
      apt-get install -y cmake && \\\nwget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb\
      \ && \\\ndpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb && \\\ncurl -k\
      \ -L https://github.com/COMBINE-lab/salmon/archive/v${SALMON_VERSION}.tar.gz\
      \ -o salmon-v${SALMON_VERSION}.tar.gz && \\\ntar xzf salmon-v${SALMON_VERSION}.tar.gz\
      \ && \\\ncd salmon-${SALMON_VERSION} && \\\nmkdir build && \\\ncd build && \\\
      \ncmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/salmon_tmp && make && make install\
      \ && \\\ncd && apt-get update && \\\napt-get install -y --no-install-recommends\
      \ libhwloc5 && \\\nrm -rf /var/lib/apt/lists/* && \\\ncp /usr/local/salmon_tmp/bin/salmon\
      \ /usr/local/bin && \\\ncp -r /usr/local/salmon_tmp/lib/* /usr/local/lib &&\
      \ \\\nrm -r /usr/local/salmon_tmp\n"
    env:
    - "SALMON_VERSION 1.10.1"
    - "TZ Europe/Brussels"
    - "PACKAGES git gcc make g++ libboost-all-dev liblzma-dev libbz2-dev ca-certificates\
      \ zlib1g-dev libcurl4-openssl-dev curl unzip autoconf apt-transport-https ca-certificates\
      \ gnupg software-properties-common wget tar"
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/salmon/quant/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/salmon/salmon_quant"
  executable: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/salmon/salmon_quant/salmon_quant"
  viash_version: "0.8.0-RC5"
  git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
