functionality:
  name: rnaseq
  namespace: workflows
  description: |
    A viash workflow for the nf-core/rnaseq pipeline.
  
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--fastq_1"
      type: file
      must_exist: true
      required: true
      multiple: true
      multiple_sep: " "
      description: Path to the sample (or read 1 of paired end sample). 
    - name: "--fastq_2"
      type: file
      required: false
      must_exist: false
      multiple: true
      multiple_sep: " "
      description: Path to read 2 of the sample.
    - name: "--strandedness"
      type: string 
      required: false
      default: auto
      choices: ["unstranded", "forward", "reverse", "auto"]
      description: Sample strand-specificity. Must be one of unstranded, forward, reverse or auto

    # Reference genome options
    - name: "--fasta"
      type: file
      description: Path to FASTA genome file.
      required: true
    - name: "--gtf"
      type: file
      description: Path to GTF annotation file. This parameter is *mandatory* if --genome is not specified.
      required: false
    - name: "--gff"
      type: file
      description: Path to GFF3 annotation file. Required if "--gtf" is not specified.
      required: false
    - name: "--additional_fasta"
      type: file
      description: FASTA file to concatenate to genome FASTA file e.g. containing spike-in sequences.
    - name: "--transcript_fasta"
      type: file
      description: Path to FASTA transcriptome file.
    - name: "--gene_bed"
      type: file
      description: Path to BED file containing gene intervals. This will be created from the GTF file if not specified.
    - name: "--splicesites"
      type: file
      description: Splice sites file required for HISAT2.
    - name: "--star_index"
      type: file
      description: Path to directory or tar.gz archive for pre-built STAR index.
    - name: "--rsem_index"
      type: file
      description: Path to directory or tar.gz archive for pre-built RSEM index.
    - name: "--salmon_index"
      type: file
      description: Path to directory or tar.gz archive for pre-built Salmon index.
    # - name: "--hisat2_index"
    #   type: file
    #   description: Path to directory or tar.gz archive for pre-built HISAT2 index.
    # - name: "--hisat2_build_memory"
    #   type: string
    #   description: Minimum memory required to use splice sites and exons in the HiSAT2 index build process.
    #   default: 200.GB
    - name: "--gencode"
      type: boolean_true
      description: Specify if the GTF annotation is in GENCODE format.
    - name: "--gtf_extra_attributes"
      type: string
      description: Additional gene identifiers from the input GTF file when running Salmon. More than one value can be specified separated by comma.
      default: gene_name
    - name: "--gtf_group_features"
      type: string
      description: Define the attribute type used to group features in the GTF file when running Salmon.
      default: gene_id
    - name: "--featurecounts_group_type"
      type: string
      description: The attribute type used to group feature types in the GTF file when generating the biotype plot with featureCounts.
      default: gene_biotype
    - name: "--featurecounts_feature_type"
      type: string
      description: By default, the pipeline assigns reads based on the 'exon' attribute within the GTF file.
      default: exon
    - name: "--save_reference"
      type: boolean
      description: If generated by the pipeline, save the STAR index in the results directory.

    # FastQC option
    - name: "--skip_fastqc"
      type: boolean
      description: Skip FatQC step.
      default: false
  
    # UMI-tools options
    - name: "--with_umi"
      type: boolean_true
      description: Enable UMI-based read deduplication.
    - name: "--skip_umi_extract"
      type: boolean
      description: Skip umi_tools extract step.
      default: false
    - name: "--umitools_extract_method"
      type: string
      description: UMI pattern to use.
      default: string
      choices: [string, regex]
    - name: "--umitools_bc_pattern"
      type: string
      description: The UMI barcode pattern to use e.g. 'NNNNNN' indicates that the first 6 nucleotides of the read are from the UMI.
    - name: "--umitools_bc_pattern2"
      type: string
      description: The UMI barcode pattern to use if the UMI is located in read 2.
    - name: "--umi_discard_read"
      type: integer
      description: After UMI barcode extraction discard either R1 or R2 by setting this parameter to 1 or 2, respectively.
      choices: [0, 1, 2]
      default: 0
    - name: "--umitools_umi_separator"
      type: string
      description: The character that separates the UMI in the read name. Most likely a colon if you skipped the extraction with UMI-tools and used other software.
      default: "_"
    - name: "--umitools_grouping_method"
      type: string
      description: Method to use to determine read groups by subsuming those with similar UMIs. All methods start by identifying the reads with the same mapping position, but treat similar yet nonidentical UMIs differently.
      choices: [ "unique", "percentile", "cluster", "adjacency", "directional" ]
      default: "directional"
    - name: "--save_umi_intermeds"
      type: boolean
      description: If this option is specified, intermediate FastQ and BAM files produced by UMI-tools are also saved in the results directory.
      default: false
    - name: "--umi_dedup_stats"
      type: boolean_true
      description: Generate output stats when running "umi_tools dedup".
  
    # Read trimming options
    - name: "--trimmer"
      type: string
      description: Specify the trimming tool to use.
      choices: [ "trimgalore", "fastp"]
      default: "trimgalore"
    - name: "--extra_trimgalore_args"
      type: string
      description: Extra arguments to pass to Trim Galore! command in addition to defaults defined by the pipeline.
    - name: "--extra_fastp_args"
      type: string
      description: Extra arguments to pass to fastp command in addition to defaults defined by the pipeline.
    - name: "--min_trimmed_reads"
      type: integer
      description: Minimum number of trimmed reads below which samples are removed from further processing. Some downstream steps in the pipeline will fail if this threshold is too low.
      default: 10000
    - name: "--skip_trimming"
      type: boolean
      description: Skip the adapter trimming step.
      default: false
    - name: "--save_trimmed"
      type: boolean
      description: Save the trimmed FastQ files in the results directory.
      default: false

    # Read filtereing options
    - name: "--bbsplit_fasta_list"
      type: file
      description: Path to comma-separated file containing a list of reference genomes to filter reads against with BBSplit. To use BBSplit, "--skip_bbsplit" must be explicitly set to "false". The file should contain 2 (comma separated) columns - short name and full path to reference genome(s)
    - name: "--bbsplit_index"
      type: file
      description: Path to directory or tar.gz archive for pre-built BBSplit index.
    - name: "--save_bbsplit_reads"
      type: boolean
      description: If this option is specified, FastQ files split by reference will be saved in the results directory.
    - name: "--skip_bbsplit"
      type: boolean
      description: Skip BBSplit for removal of non-reference genome reads.
      default: true
    - name: "--remove_ribo_rna"
      type: boolean
      description: Enable the removal of reads derived from ribosomal RNA using SortMeRNA.
    - name: "--ribo_database_manifest"
      type: file
      description: Text file containing paths to fasta files (one per line) that will be used to create the database for SortMeRNA.
      default: assets/rrna-db-defaults.txt
    - name: "--save_non_ribo_reads"
      type: boolean
      description: If this option is specified, intermediate FastQ files containing non-rRNA reads will be saved in the results directory.
    - name: "--min_mapped_reads"
      type: integer
      description: Minimum percentage of uniquely mapped reads below which samples are removed from further processing.
      default: 5

    # Alignment options
    - name: "--bam_csi_index"
      type: boolean_true
      description: Create a CSI index for BAM files instead of the traditional BAI index. This will be required for genomes with larger chromosome sizes.
    - name: "--extra_star_align_args"
      type: string
      default: '--readFilesCommand gunzip -c --quantMode TranscriptomeSAM --twopassMode Basic --outSAMtype BAM Unsorted --runRNGseed 0 --outFilterMultimapNmax 20 --alignSJDBoverhangMin 1 --outSAMattributes NH HI AS NM MD --quantTranscriptomeBan Singleend --outSAMstrandField intronMotif'
      description: Extra arguments to pass to STAR alignment command in addition to defaults defined by the pipeline.
    - name: "--star_ignore_sjdbgtf"
      type: boolean_true
      description: When using pre-built STAR indices, do not re-extract and use splice junctions from the GTF file. 
    - name: "--seq_platform"
      type: string
      description: Sequencing platform.
    - name: "--seq_center"
      type: string
      description: Sequencing center.
    - name: "--salmon_quant_libtype"
      type: string
      description: Override Salmon library type inferred based on strandedness defined in meta object.
    - name: "--extra_salmon_quant_args"
      type: string
      default: '-v'
      description: Extra arguments to pass to salmon quant command in addition to defaults defined by the pipeline.
    - name: "--stringtie_ignore_gtf"
      type: boolean_true
      description: Perform reference-guided de novo assembly of transcripts using StringTie, i.e. don't restrict to those in GTF file.
    - name: "--extra_stringtie_args"
      type: string
      default: '-v'
      description: Extra arguments to pass to stringtie command in addition to defaults defined by the pipeline.

    # Extra pipeline options:
    - name: "--skip_qc"
      type: boolean_true
      description: Skip QC steps of the workflow.
    - name: "--skip_markdupkicates"
      type: boolean_true
    - name: "--skip_stringtie"
      type: boolean_true
    - name: "--skip_biotype_qc"
      type: boolean_true
    - name: "--skip_bigwig"
      type: boolean_true
    - name: "--with_preseq"
      type: boolean_true
    - name: "--extra_fq_subsample_args"
      type: string
      default: '--record-count 1000000 --seed 1'
      description: Extra arguments to pass to fq subsample command in addition to defaults defined by the pipeline.
    - name: "--extra_picard_args"
      type: string
      default: '--ASSUME_SORTED true --REMOVE_DUPLICATES false --VALIDATION_STRINGENCY LENIENT --TMP_DIR tmp'
      description: Extra arguments to pass to picard MarkDuplicates command in addition to defaults defined by the pipeline.
    - name: "--extra_bedtools_args"
      type: string
      default: '-split -du'
      description: Extra arguments to pass to bedtools genomecov command in addition to defaults defined by the pipeline.
    - name: "--extra_featurecounts_args"
      type: string
      description: Extra arguments to pass to featureCounts command in addition to defaults defined by the pipeline
      default: '-B -C'
    - name: "--extra_preseq_args"
      type: string
      description: Extra arguments to pass to preseq lc_extrap command in addition to defaults defined by the pipeline
      default: '-verbose -bam -seed 1 -seg_len 100000000'
    - name: "--pca_header_multiqc"
      type: file
      default: assets/multiqc/deseq2_pca_header.txt
    - name: "--clustering_header_multiqc"
      type: file
      default: assets/multiqc/deseq2_clustering_header.txt
    - name: "--deseq2_vst"
      type: boolean
      default: true
      description: Use vst transformation instead of rlog with DESeq2
    - name: "--extra_deseq2_args"
      type: string
      default: "--id_col 1 --sample_suffix '' -outprefix deseq2 --count_col 3"
    - name: "--extra_deseq2_args2"
      type: string
      default: star_salmon

    # Multiqc paramenters
    - name: "--multiqc_custom_config"
      type: file
    - name: "--multiqc_title"
      type: string
    - name: "--multiqc_logo"
      type: file
    - name: "--multiqc_methods_description"
      type: file
      default: assets/methods_description_template.yml
     
    - name: "--output"
      type: file
      description: Path to output directory
      direction: output

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf

  dependencies: 
    - name: workflows/prepare_genome
    - name: cat_fastq
    - name: workflows/pre_processing
    - name: workflows/genome_alignment_and_quant
    - name: workflows/post_processing
    - name: workflows/final_qc

platforms:
  - type: nextflow
    directives: 
      label: [ "lowtime", "lowmem", "lowcpu" ]
