functionality:
  name: "bbmap_bbsplit"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/nf-core/bbmap/bbsplit/main.nf, modules/nf-core/bbmap/bbsplit/meta.yml]
      last_sha: 277bd337739a8b8f753fa7b5eda6743b9b6acb89
  description: |
    Split sequencing reads by mapping them to multiple references simultaneously.
  arguments:
    # Inputs
    - name: "--id"
      type: string
      description: Sample ID
    - name: "--paired"
      type: boolean 
      default: false
      description: Paired fastq files or not?
    - name: "--input"
      type: file
      multiple: true
      multiple_sep: ","
      description: Input fastq files, either one or two (paired)
      example: sample.fastq
    - name: "--primary_ref"
      type: file
      description: Primary reference FASTA
    - name: "--bbsplit_fasta_list"
      type: file
      description: Path to comma-separated file containing a list of reference genomes to filter reads against with BBSplit.
    - name: "--only_build_index"
      type: boolean
      description: true = only build index; false = mapping
    - name: "--build"
      type: integer
      description: Designate index to use.  Corresponds to the number specified when building the index. If multiple references are indexed in the same directory, each needs a unique build ID.
      default: 1
    - name: "--built_bbsplit_index"
      type: file
      description: Directory with index files
      
    - name: "--bbsplit_index"
      type: file
      description: Directory with index files
      direction: output
    
    # Outputs
    - name: "--fastq_1"
      type: file
      required: false
      description: Output file for read 1.
      direction: output
      default: $id.$key.read1.fq.gz
    - name: "--fastq_2"
      type: file
      required: false
      must_exist: false
      description: Output file for read 2.
      direction: output
      default: $id.$key.read2.fq.gz

  resources:
    - type: bash_script
      path: script.sh
  
  test_resources:
    - type: bash_script
      path: test.sh
    - path: test_resources/fastq_data_dir

platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: docker
        run: | 
          apt-get update && \
          apt-get install -y build-essential openjdk-17-jdk wget tar && \
          wget --no-check-certificate https://sourceforge.net/projects/bbmap/files/BBMap_39.01.tar.gz && \
          tar xzf BBMap_39.01.tar.gz && \
          cp -r bbmap/* /usr/local/bin
  - type: nextflow
