functionality:
  name: "samtools_idxstats"
  namespace: "samtools"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/nf-core/samtools/idxstats/main.nf, modules/nf-core/samtools/idxstats/meta.yml]
      last_sha: 54721c6946daf6d602d7069dc127deef9cbe6b33

  description: |
    Reports alignment summary statistics for a BAM file
  arguments:
    - name: "--bam"
      type: file
      description: BAM input files.
    - name: "--bai"
      type: file
      description: BAM index file.
    - name: "--fasta"
      type: file
      description: Reference file the CRAM was created with (optional).
    
    - name: "--output"
      type: file 
      description: File containing samtools stats output.
      direction: output
      default: $id.$key.idxstats

  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
platforms:
  - type: nextflow
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: docker
        env: 
          - PACKAGES build-essential gcc g++ autoconf automake make wget zlib1g-dev unzip autoconf make gcc perl libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev bzip2 gawk
        run: |
          apt-get update && \
          apt-get install -y --no-install-recommends ${PACKAGES} && \
          wget --no-check-certificate https://github.com/samtools/samtools/releases/download/1.18/samtools-1.18.tar.bz2 && \
          tar -xjf samtools-1.18.tar.bz2 && \
          rm samtools-1.18.tar.bz2 && \
          cd samtools-1.18 && \
          ./configure && \
          make && \
          make install && \
          cd
  - type: nextflow
  