name: "rseqc_inferexperiment"
namespace: "rseqc"
info:
  migration_info:
    git_repo: https://github.com/nf-core/rnaseq.git
    paths: [modules/nf-core/rseqc/inferexperiment/main.nf]
    last_sha: 54721c6946daf6d602d7069dc127deef9cbe6b33
description: |
  Infer strandedness from sequencing reads

argument_groups:
- name: "Input"
  arguments: 
  - name: "--input"
    type: file 
    required: true
    description: input alignment file in BAM or SAM format

  - name: "--refgene"
    type: file 
    required: true
    description: Reference gene model in bed format

  - name: "--sample_size"
    type: integer
    required: false
    default: 200000
    min: 1
    description: Numer of reads sampled from SAM/BAM file, default = 200000.

  - name: "--map_qual"
    type: integer
    required: false
    default: 30 
    description: Minimum mapping quality (phred scaled) to determine uniquely mapped reads, default=30.
    min: 0
  
- name: "Output"
  arguments: 
  - name: "--output"
    type: file
    direction: output
    required: false
    default: $id.strandedness.txt
    description: output file (txt) of strandness report

resources:
  - type: bash_script
    path: script.sh

test_resources:
  - type: bash_script
    path: test.sh
  - path: /testData/unit_test_resources/sarscov2/test.paired_end.sorted.bam
  - path: /testData/unit_test_resources/sarscov2/test.bed12

engines:
- type: docker
  image: ubuntu:22.04
  setup:   
    - type: apt
      packages: [ python3-pip ]
    - type: python
      packages: [ RSeQC ]
runners: 
- type: executable
- type: nextflow
  directives:
    label: [ midmem, midcpu ]
