name: "rsem_prepare_reference"
namespace: "rsem"
info:
  migration_info:
    git_repo: https://github.com/nf-core/rnaseq.git
    paths: [modules/nf-core/rsem/preparereference/main.nf, modules/nf-core/rsem/preparereference/meta.yml]
    last_sha: 92b2a7857de1dda9d1c19a088941fc81e2976ff7

description: | 
  Prepare a reference genome for RSEM.

argument_groups:
- name: "Input"
  arguments: 
  - name: "--fasta"
    type: file
    description: Genome fasta file
  - name: "--gtf"
    type: file
    description: GTF file
  - name: "--star"
    type: boolean
  - name: "--versions"
    type: file
    must_exist: false
  
- name: "Output"
  arguments: 
  - name: "--rsem"
    type: file
    direction: output
    description: RSEM index directory.
  - name: "--transcript_fasta"
    type: file
    direction: output
    description: Fasta file of transcripts
  - name: "--updated_versions"
    type: file
    default: versions.yml
    direction: output

resources:
  - type: bash_script
    path: script.sh

test_resources:
  - type: bash_script
    path: test.sh
  - path: /testData/minimal_test/reference/genome.fasta
  - path: /testData/minimal_test/reference/genes.gtf.gz
  
engines:
- type: docker
  image: ubuntu:22.04
  setup:
    - type: docker
      run: |
        apt-get update && \
        apt-get install -y --no-install-recommends build-essential gcc g++ make wget zlib1g-dev unzip && \
        apt-get clean && \
        wget --no-check-certificate https://github.com/alexdobin/STAR/archive/refs/tags/2.7.11a.zip && \
        unzip 2.7.11a.zip && \
        cp STAR-2.7.11a/bin/Linux_x86_64_static/STAR /usr/local/bin  && \
        cd && \
        wget --no-check-certificate https://github.com/deweylab/RSEM/archive/refs/tags/v1.3.3.zip && \
        unzip v1.3.3.zip && \
        cd RSEM-1.3.3 && \
        make && \
        make install
runners: 
- type: executable
- type: nextflow