functionality:
  name: post_processing
  namespace: workflows
  description: |
    A viash sub-workflow for the post-processing stage of nf-core/rnaseq pipeline.
  
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--strandedness"
      type: string 
      required: false
      default: auto
      description: Sample strand-specificity. Must be one of unstranded, forward, reverse or auto
    - name: "--paired"
      type: boolean 
      required: false
      default: false
      description: Paired fastq files or not?
    - name: "--fasta"
      type: file
      description: Path to FASTA genome file.
      required: true
    - name: "--fai"
      type: file
      description: Path to FASTA index
      required: true
    - name: "--gtf"
      type: file
      description: GTF file
    - name: "--genome_bam"
      type: file
      description: Genome BAM file
    - name: "--chrom_sizes"
      type: file
      description: File containing chromosome lengths
    - name: "--star_multiqc"
      type: file
      description: STAR align log file.
    - name: "--extra_picard_args"
      type: string
      default: ''
      description: Extra arguments to pass to picard MarkDuplicates command in addition to defaults defined by the pipeline.
    - name: "--extra_stringtie_args"
      type: string
      default: ''
      description: Extra arguments to pass to stringtie command in addition to defaults defined by the pipeline.
    - name: "--stringtie_ignore_gtf"
      type: boolean
      description: Perform reference-guided de novo assembly of transcripts using StringTie, i.e. don't restrict to those in GTF file.
    - name: "--extra_bedtools_args"
      type: string
      default: ''
      description: Extra arguments to pass to bedtools genomecov command in addition to defaults defined by the pipeline.
    - name: "--extra_featurecounts_args"
      type: string
      description: Extra arguments to pass to featureCounts command in addition to defaults defined by the pipeline
      default: '-B -C'
    - name: "--bam_csi_index"
      type: boolean
      default: false
      description: Create a CSI index for BAM files instead of the traditional BAI index. This will be required for genomes with larger chromosome sizes.
    - name: "--min_mapped_reads"
      type: integer
      description: Minimum percentage of uniquely mapped reads below which samples are removed from further processing.
    - name: "--with_umi"
      type: boolean
      description: Enable UMI-based read deduplication.
      default: false
    - name: "--biotype"
      type: string
      description: Biotype value to use while appending entries to GTF file when additional fasta file is provided.
    - name: "--biotypes_header"
      type: file
      default: assets/multiqc/biotypes_header.txt
    - name: "--skip_qc"
      type: boolean
    - name: "--skip_markdupkicates"
      type: boolean
    - name: "--skip_stringtie"
      type: boolean
    - name: "--skip_biotype_qc"
      type: boolean
    - name: "--skip_bigwig"
      type: boolean
    - name: "--featurecounts_group_type"
      type: string
      description: The attribute type used to group feature types in the GTF file when generating the biotype plot with featureCounts.
      default: gene_biotype
    - name: "--featurecounts_feature_type"
      type: string
      description: By default, the pipeline assigns reads based on the 'exon' attribute within the GTF file.
      default: exon
    - name: "--gencode"
      type: boolean
      description: Specify if the GTF annotation is in GENCODE format.

    # Output
    - name: "--processed_genome_bam"
      type: file
      direction: output
    - name: "--genome_bam_indexed"
      type: file
      direction: output
    - name: "--genome_bam_stats"
      type: file
      direction: output
    - name: "--genome_bam_flagstat"
      type: file
      direction: output
    - name: "--genome_bam_idxstats"
      type: file
      direction: output
    - name: "--stringtie_transcript_gtf"
      type: file
      direction: output
    - name: "--transcript_gtf"
      type: file
      direction: output
    - name: "--stringtie_coverage_gtf"
      type: file
      direction: output
    - name: "--stringtie_abundance"
      type: file
      direction: output
    - name: "--stringtie_ballgown"
      type: file
      direction: output
    - name: "--featurecounts"
      type: file
      direction: output
    - name: "--featurecounts_summary"
      type: file
      direction: output
    - name: "--featurecounts_multiqc"
      type: file
      direction: output
    - name: "--bedgraph_forward"
      type: file
      direction: output
    - name: "--bedgraph_reverse"
      type: file
      direction: output
    - name: "--bigwig_forward"
      type: file
      direction: output
    - name: "--bigwig_reverse"
      type: file
      direction: output

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  
  dependencies:
    - name: picard_markduplicates
    - name: samtools/samtools_sort
    - name: samtools/samtools_index
    - name: samtools/samtools_stats
    - name: samtools/samtools_flagstat
    - name: samtools/samtools_idxstats
    - name: stringtie
    - name: subread_featurecounts
    - name: multiqc_custom_biotype
    - name: bedtools_genomecov
    - name: ucsc/ucsc_bedclip
    - name: ucsc/ucsc_bedgraphtobigwig

platforms:
  - type: nextflow