functionality:
  name: genome_alignment_and_quant
  namespace: workflows
  description: |
    A viash sub-workflow for genome alignment and quantification stage of nf-core/rnaseq pipeline.
  
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--fastq_1"
      alternatives: [-i]
      type: file
      description: Path to the sample (or read 1 of paired end sample).
      required: true
      example: input.fastq.gz
    - name: "--fastq_2"
      type: file
      required: false
      description: Path to read 2 of the sample.
    - name: "--strandedness"
      type: string 
      required: false
      default: auto
      description: Sample strand-specificity. Must be one of unstranded, forward, reverse or auto
    - name: "--gtf"
      type: file
      description: GTF file
    - name: "--transcript_fasta"
      type: file
      description: Fasta file of the reference transcriptome.
    - name: "--star_index"
      type: file
      description: STAR index directory.
    - name: "--star_ignore_sjdbgtf"
      type: boolean
      default: false
      description: When using pre-built STAR indices do not re-extract and use splice junctions from the GTF file 
    - name: "--seq_platform"
      type: string
      description: Sequencing platform.
    - name: "--seq_center"
      type: string
      description: Sequencing center.
    - name: "--extra_star_align_args"
      type: string
      default: ''
      description: Extra arguments to pass to STAR alignment command in addition to defaults defined by the pipeline.
    - name: "--bam_csi_index"
      type: boolean
      default: false
      description: Create a CSI index for BAM files instead of the traditional BAI index. This will be required for genomes with larger chromosome sizes.
    - name: "--umi_dedup_stats"
      type: boolean
      description: Generate output stats when running "umi_tools dedup".
      default: false
    - name: "--with_umi"
      type: boolean
      description: Enable UMI-based read deduplication.
      default: false
    - name: "--salmon_quant_libtype"
      type: string
      description: Override Salmon library type inferred based on strandedness defined in meta object.
    - name: "--extra_salmon_quant_args"
      type: string
      default: ''
      description: Extra arguments to pass to salmon quant command in addition to defaults defined by the pipeline.
    - name: "--gtf_group_features"
      type: string
      default: 'gene_id'
      description: Define the attribute type used to group features in the GTF file when running Salmon.
    - name: "--gtf_extra_attributes"
      type: string
      default: 'gene_name'
      description: By default, the pipeline uses the gene_name field to obtain additional gene identifiers from the input GTF file when running Salmon.

    # Output
    - name: "--star_alignment"
      type: file
      direction: output
    - name: "--star_multiqc"
      type: file
      direction: output
    - name: "--genome_bam_indexed"
      type: file
      direction: output
    - name: "--genome_bam_stats"
      type: file
      direction: output
    - name: "--genome_bam_flagstat"
      type: file
      direction: output
    - name: "--genome_bam_idxstats"
      type: file
      direction: output
    - name: "--transcriptome_bam_indexed"
      type: file
      direction: output
    - name: "--transcriptome_bam_stats"
      type: file
      direction: output
    - name: "--transcriptome_bam_flagstat"
      type: file
      direction: output
    - name: "--transcriptome_bam_idxstats"
      type: file
      direction: output
    - name: "--salmon_quant_results"
      type: file
      direction: output
    - name: "--salmon_tx2gene"
      type: file
      direction: output
    - name: "--salmon_tximport"
      type: file
      direction: output
    - name: "--salmon_summarizedexperiment"
      type: file
      direction: output

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  
  dependencies:
    - name: star/star_align
    - name: samtools/samtools_sort
    - name: samtools/samtools_index
    - name: samtools/samtools_stats
    - name: samtools/samtools_flagstat
    - name: samtools/samtools_idxstats
    - name: umitools/umitools_dedup
    - name: umitools_prepareforquant
    - name: salmon/salmon_quant
    - name: salmon/salmon_tx2gene
    - name: salmon/salmon_tximport
    - name: salmon/salmon_summarizedexperiment

platforms:
  - type: nextflow