functionality:
  name: "rsem_calculate_expression"
  namespace: "rsem"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/nf-core/rsem/calculateexpression/main.nf, modules/nf-core/rsem/calculateexpression/meta.yml]
      last_sha: 92b2a7857de1dda9d1c19a088941fc81e2976ff7

  description: | 
    Calculate expression with RSEM.

  arguments:
  - name: "--id"
    type: string
    description: Sample ID.
  - name: "--strandedness"
    type: string
    description: Sample strand-specificity. Must be one of unstranded, forward, reverse
    choices: [forward, reverse, unstranded]
  - name: "--paired"
    type: boolean
    description: Paired-end reads or not?
  - name: "--input"
    type: file
    description: Input reads for quantification.
    multiple: true
    multiple_sep: ","
  - name: "--index"
    type: file
    description: RSEM index.  
  - name: "--extra_args"
    type: string
    description: Extra rsem-calculate-expression arguments in addition to the defaults.
  - name: "--versions"
    type: file
    must_exist: false

  - name: "--counts_gene"
    type: file
    description: Expression counts on gene level
    default: $id.genes.results
    direction: output
  - name: "--counts_transctips"
    type: file
    description: Expression counts on transcript level
    default: $id.isoforms.results
    direction: output
  - name: "--stat"
    type: file
    description: RSEM statistics
    default: $id.stat
    direction: output
  - name: "--logs"
    type: file
    description: RSEM logs
    default: $id.log
    direction: output
  - name: "--bam_star"
    type: file
    description: BAM file generated by STAR (optional)
    default: $id.STAR.genome.bam
    direction: output
  - name: "--bam_genome"
    type: file
    description: Genome BAM file (optional)
    default: $id.genome.bam
    direction: output
  - name: "--bam_transcript"
    type: file
    description: Transcript BAM file (optional)
    default: $id.transcript.bam
    direction: output
  - name: "--updated_versions"
    type: file
    default: versions.yml
    direction: output

  resources:
    - type: bash_script
      path: script.sh
  
  test_resources:
    - type: bash_script
      path: test.sh
    - path: /testData/minimal_test/input_fastq/SRR6357070_1.fastq.gz
    - path: /testData/minimal_test/input_fastq/SRR6357070_2.fastq.gz
    - path: /testData/minimal_test/reference/rsem.tar.gz

# TODO: Install bowtie/bowtie2 
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: docker
        run: |
          apt-get update && \
          apt-get install -y --no-install-recommends build-essential gcc g++ make wget zlib1g-dev unzip && \
          apt-get clean && \
          wget --no-check-certificate https://github.com/alexdobin/STAR/archive/refs/tags/2.7.11a.zip && \
          unzip 2.7.11a.zip && \
          cp STAR-2.7.11a/bin/Linux_x86_64_static/STAR /usr/local/bin  && \
          cd && \
          wget --no-check-certificate https://github.com/deweylab/RSEM/archive/refs/tags/v1.3.3.zip && \
          unzip v1.3.3.zip && \
          cd RSEM-1.3.3 && \
          make && \
          make install
  - type: nextflow