functionality:
  name: "rseqc_bamstat"
  namespace: "rseqc"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/nf-core/rseqc/bamstat/main.nf]
      last_sha: 54721c6946daf6d602d7069dc127deef9cbe6b33
  description: |
    Generate statistics from a bam file.

  arguments:
    - name: "--input"
      type: file 
      required: true
      description: bam file to calculate statistics of

    - name: "--map_qual"
      type: integer
      required: false
      default: 30 
      description: Minimum mapping quality (phred scaled) to determine uniquely mapped reads. default=30.
      min: 0
    
    - name: "--output"
      type: file
      direction: output
      required: true
      description: directory for output of bam statistics report

  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
    - path: /testData/test/SRR6357070.bam
   
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:   
      - type: apt
        packages: [ python3-pip ]
      - type: python
        packages: [ RSeQC ]
  - type: nextflow
