name: "tx2gene"
info:
  migration_info:
    git_repo: https://github.com/nf-core/rnaseq.git
    paths: [modules/local/tx2gene/main.nf]
    last_sha: 839ac5cab892504514cc96d44e99e70516b239d2
description: Get transcript id (tx) to gene names for tximport

argument_groups:
- name: "Input"
  arguments:  
  - name: "--quant_results"
    type: file
    multiple: true
    multiple_sep: ";"
  - name: "--gtf"
    type: file
  - name: "--gtf_extra_attributes"
    type: string
    default: 'gene_name'
  - name: "--gtf_group_features"
    type: string
    default: 'gene_id'
  - name: "--quant_type"
    type: string
    description: Method used for quantification
    choices: ["salmon", "kallisto"]
    
- name: "Output"
  arguments:   
  - name: "--tsv"
    type: file
    direction: output
    default: tx2gene.tsv

resources:
  - type: bash_script
    path: script.sh
  # copied from https://github.com/nf-core/rnaseq/blob/3.14.0/bin/tx2gene.py
  - path: tx2gene.py

test_resources:
  - type: bash_script
    path: test.sh
    
engines:
- type: docker
  image: ubuntu:22.04
  setup:
    - type: apt
      packages: [pip, unzip]
    - type: python
runners: 
- type: executable
- type: nextflow
