functionality:
  name: pre_processing
  namespace: workflows
  description: |
    A subworkflow for stage 1 of the nf-core/rnaseq pipeline.
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          alternatives: [-i]
          description: Path to the sample.
          required: true
          example: input.fastq.gz
          type: file
    - name: Output
      arguments:
        - name: "--output"
          type: string
          description: Path to output directory
          required: true
  arguments:
    - name: "--umitools_bc_pattern"
      type: string

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    - name: qc/fastqc
      repository: local
    - name: qc/umitools_extract
      repository: local
  repositories:
    - name: openpipeline_modules
      type: git
      uri: https://github.com/openpipelines-bio/openpipeline
      tag: 0.9.0
    - name: local
      type: local
platforms:
  - type: nextflow