functionality:
  name: pre_processing
  namespace: workflows
  description: |
    A subworkflow for stage 1 of the nf-core/rnaseq pipeline.
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          alternatives: [-i]
          description: Path to the sample (or read 1 of paired end sample).
          required: true
          example: input.fastq.gz
          type: file
        - name: "--input2"
          description: Path to read 2 of the sample.
          required: false
          example: input.fastq.gz
          type: file
    - name: Output
      arguments:
        - name: "--output"
          type: file
          description: Path to output directory
          required: true
  
  arguments:
  # FastQC option
    - name: "--skip_fastqc"
      type: boolean
      description: Skip FatQC step.
      default: false
  
  # UMI-tools options
    - name: "--skip_umitools_extract"
      type: boolean
      description: Skip umi_tools extract step.
      default: false
    - name: "--umitools_extract_method"
      type: string
      description: UMI pattern to use.
      default: string
      choices: [string, regex]
    - name: "--umitools_bc_pattern"
      type: string
      description: "The UMI barcode pattern to use e.g. 'NNNNNN' indicates that the first 6 nucleotides of the read are from the UMI."
    - name: "--umitools_bc_pattern2"
      type: string
      description: The UMI barcode pattern to use if the UMI is located in read 2.
    - name: "--umitools_umi_separator"
      type: string
      description: The character that separates the UMI in the read name. Most likely a colon if you skipped the extraction with UMI-tools and used other software.
      default: "_"
    - name: "--save_umi_intermeds"
      type: boolean
      description: If this option is specified, intermediate FastQ and BAM files produced by UMI-tools are also saved in the results directory.
      default: false
  
  # Trimgalore options


  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    - name: qc/fastqc
      repository: local
    - name: qc/umitools_extract
      repository: local
  repositories:
    - name: openpipeline_modules
      type: git
      uri: https://github.com/openpipelines-bio/openpipeline
      tag: 0.9.0
    - name: local
      type: local
platforms:
  - type: nextflow