functionality: 
  name: stringtie
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/nf-core/stringtie/stringtie/main.nf, modules/nf-core/stringtie/stringtie/meta.yml]
      last_sha: 55398de6ab7577acfe9b1180016a93d7af7eb859
  description: | 
    Transcript assembly and quantification for RNA-Seq

  arguments:
    
    # Input
    - name: "--strandedness"
      type: string
      description: Forward or reverse strand?
    - name: "--bam"
      type: file
    - name: "--annotation_gtf"
      type: file
    - name: "--extra_stringtie_args"
      type: string
      description: Extra arguments for running StringTie
    - name: "--stringtie_ignore_gtf"
      type: boolean
      description: Perform reference-guided de novo assembly of transcripts using StringTie, i.e. don't restrict to those in GTF file.

    # Output
    - name: "--transcript_gtf"
      type: file
      default: $id.$key.transcripts.gtf
      direction: output
    - name: "--coverage_gtf"
      type: file
      default: $id.$key.coverage.gtf
      direction: output
    - name: "--abundance"
      type: file
      default: $id.$key.abundance.txt
      direction: output
    - name: "--ballgown"
      type: file
      description: for running ballgown
      default: $id.$key.ballgown
      direction: output

  resources: 
    - type: bash_script
      path: script.sh
  
  test_resources:
    - type: bash_script
      path: test.sh
    - path: testData/reference/genes.gtf.gz
    - path: testData/minimal_test/test.bam  # add test BAM file

platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: docker
        run: | 
          apt-get update && \
          apt-get install -y build-essential zlib1g wget && \
          wget --no-check-certificate https://github.com/gpertea/stringtie/releases/download/v2.2.1/stringtie-2.2.1.Linux_x86_64.tar.gz && \
          tar -xzf stringtie-2.2.1.Linux_x86_64.tar.gz && \
          cp stringtie-2.2.1.Linux_x86_64/stringtie /usr/local/bin/
  - type: nextflow
