functionality:
  name: "check_contig_size"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [lib/WorkflowRnaseq.groovy]
      last_sha: 993fff67ba7590c85cb107143513943ff39dbd21
  description: Check if contigs in genome fasta file > 512 Mbp

  arguments:
    - name: "--input"
      type: file

  resources:
    - type: python_script
      path: script.py

platforms: 
- type: docker
  image: python:latest
  setup:
    - type: python
- type: nextflow