functionality:
  name: "umitools_dedup"
  namespace: "umitools"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/nf-core/umitools/dedup/main.nf, modules/nf-core/umitools/dedup/meta.yml]
      last_sha: 54721c6946daf6d602d7069dc127deef9cbe6b33
  description: |
    Deduplicate reads based on the mapping co-ordinate and the UMI attached to the read.
  
  arguments:
    # Inputs
    - name: "--paired"
      type: boolean 
      default: false
      description: Paired fastq files or not?
    - name: "--bam"
      type: file
      description: Input BAM file
    - name: "--bai"
      type: file
      description: BAM index
    - name: "--get_output_stats"
      type: boolean
      description: Whether or not to generate output stats.
    
    # Outputs
    - name: "--output_bam"
      type: file
      description: Deduplicated BAM file
      direction: output
      default: $id.$key.bam
    - name: "--output_stats"
      type: file
      description: Directory containing UMI based dedupllication statistics files
      default: $id.umi_dedup.stats

  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: apt
        packages: [pip]
      - type: python
        packages: [umi-tools]
  - type: nextflow

 
  
  
