name: "rsem_calculate_expression"
namespace: "rsem"
version: "main_build"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "string"
    name: "--id"
    description: "Sample ID."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--strandedness"
    description: "Sample strand-specificity. Must be one of unstranded, forward, reverse"
    info: null
    required: false
    choices:
    - "forward"
    - "reverse"
    - "unstranded"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--paired"
    description: "Paired-end reads or not?"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input"
    description: "Input reads for quantification."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ","
  - type: "file"
    name: "--index"
    description: "RSEM index."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--extra_args"
    description: "Extra rsem-calculate-expression arguments in addition to the defaults."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--versions"
    info: null
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--counts_gene"
    description: "Expression counts on gene level"
    info: null
    default:
    - "$id.genes.results"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--counts_transctips"
    description: "Expression counts on transcript level"
    info: null
    default:
    - "$id.isoforms.results"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--stat"
    description: "RSEM statistics"
    info: null
    default:
    - "$id.stat"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--logs"
    description: "RSEM logs"
    info: null
    default:
    - "$id.log"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--bam_star"
    description: "BAM file generated by STAR (optional)"
    info: null
    default:
    - "$id.STAR.genome.bam"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--bam_genome"
    description: "Genome BAM file (optional)"
    info: null
    default:
    - "$id.genome.bam"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--bam_transcript"
    description: "Transcript BAM file (optional)"
    info: null
    default:
    - "$id.transcript.bam"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--updated_versions"
    info: null
    default:
    - "versions.yml"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "bash_script"
  path: "script.sh"
  is_executable: true
description: "Calculate expression with RSEM.\n"
test_resources:
- type: "bash_script"
  path: "test.sh"
  is_executable: true
- type: "file"
  path: "testData/minimal_test/input_fastq/SRR6357070_1.fastq.gz"
- type: "file"
  path: "testData/minimal_test/input_fastq/SRR6357070_2.fastq.gz"
- type: "file"
  path: "testData/minimal_test/reference/rsem.tar.gz"
info:
  migration_info:
    git_repo: "https://github.com/nf-core/rnaseq.git"
    paths:
    - "modules/nf-core/rsem/calculateexpression/main.nf"
    - "modules/nf-core/rsem/calculateexpression/meta.yml"
    last_sha: "92b2a7857de1dda9d1c19a088941fc81e2976ff7"
status: "enabled"
requirements:
  commands:
  - "ps"
runners:
- type: "executable"
  id: "docker"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "ubuntu:22.04"
  target_organization: "data-intuitive"
  target_registry: "ghcr.io"
  target_tag: "main_build"
  namespace_separator: "/"
  target_image_source: "https://github.com/data-intuitive/rnaseq.vsh"
  setup:
  - type: "docker"
    run:
    - "apt-get update && \\\napt-get install -y --no-install-recommends build-essential\
      \ gcc g++ make wget zlib1g-dev unzip && \\\napt-get clean && \\\nwget --no-check-certificate\
      \ https://github.com/alexdobin/STAR/archive/refs/tags/2.7.11a.zip && \\\nunzip\
      \ 2.7.11a.zip && \\\ncp STAR-2.7.11a/bin/Linux_x86_64_static/STAR /usr/local/bin\
      \  && \\\ncd && \\\nwget --no-check-certificate https://github.com/deweylab/RSEM/archive/refs/tags/v1.3.3.zip\
      \ && \\\nunzip v1.3.3.zip && \\\ncd RSEM-1.3.3 && \\\nmake && \\\nmake install\n"
  entrypoint: null
  cmd: null
build_info:
  config: "src/rsem/rsem_calculate_expression/config.vsh.yaml"
  runner: "docker"
  engine: "docker"
  output: "target/docker/rsem/rsem_calculate_expression"
  executable: "target/docker/rsem/rsem_calculate_expression/rsem_calculate_expression"
  viash_version: "0.9.0-RC2"
  git_commit: "f1bac79d3ebb4bff084f592da4371d1e3a1a6865"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh"
package_config:
  info: null
  viash_version: "0.9.0-RC2"
  source: "src"
  target: "target"
  config_mods:
  - ".version := 'dev'\n.requirements.commands := ['ps']\n.engines[.type == 'docker'].target_registry\
    \ := 'ghcr.io'\n.engines[.type == 'docker'].target_organization := 'data-intuitive'\n\
    .engines[.type == 'docker'].target_image_source := 'https://github.com/data-intuitive/rnaseq.vsh'\n\
    .runners[.type == 'nextflow'].directives.tag := '$id'\n.runners[.type == 'nextflow'].auto.simplifyOutput\
    \ := false"
  - ".version := \"main_build\""
  - ".engines[.type == 'docker'].target_tag := 'main_build'"
