name: prepare_genome
description: |
  Prepare genome and transcriptome FASTA files for STAR alignment by adding
  necessary headers and creating a STAR index.

argument_groups:
  - name: Inputs
    arguments:
      - name: --input_genome_fasta
        type: file
        example: "genome.fasta.gz"
      - name: --input_transcriptome_gtf
        type: file
        example: "genes.gtf.gz"
  - name: Outputs
    arguments:
      - name: --output_genome_fasta
        type: file
        direction: output
        example: "genome.fasta"
      - name: --output_transcriptome_gtf
        type: file
        direction: output
        example: "transcriptome.gtf"
      - name: --output_star_index
        type: file
        direction: output

dependencies:
  - name: bgzip
    repository: toolbox

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run

runners:
  - type: nextflow
