functionality:
  name: "rseqc_inferexperiment"
  namespace: "rseqc"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/nf-core/rseqc/inferexperiment/main.nf]
      last_sha: 54721c6946daf6d602d7069dc127deef9cbe6b33
  description: |
    Infer strandedness from sequencing reads

  arguments:
    - name: "--input"
      type: file 
      required: true
      description: input alignment file in BAM or SAM format

    - name: "--refgene"
      type: file 
      required: true
      description: Reference gene model in bed format

    - name: "--sample_size"
      type: integer
      required: false
      default: 200000
      min: 1
      description: Numer of reads sampled from SAM/BAM file, default = 200000.

    - name: "--map_qual"
      type: integer
      required: false
      default: 30 
      description: Minimum mapping quality (phred scaled) to determine uniquely mapped reads, default=30.
      min: 0
    
    - name: "--output"
      type: file
      direction: output
      required: false
      default: $id.strandedness.txt
      description: output file (txt) of strandness report

  resources:
    - type: bash_script
      path: script.sh

  test_resources:
    - type: bash_script
      path: test.sh
    - path: /testData/test/SRR6357070.bam
    - path: /testData/test/genome_gfp.bed

platforms:
  - type: docker
    image: ubuntu:22.04
    setup:   
      - type: apt
        packages: [ python3-pip ]
      - type: python
        packages: [ RSeQC ]
  - type: nextflow
