functionality:
  name: "fastqc"
  namespace: "qc"
  description: |
    Fastqc component, please see https://www.bioinformatics.babraham.ac.uk/projects/fastqc/. This component can take one or more files (by means of shell globbing) or a complete directory.
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      description: Input fastq files (read1 of paired-end data).
      example: sample.fastq\
    - name: "--input_r2"
      type: file
      description: Input fastq files (read2 of paired-end data).
      example: sample_2.fastq
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      direction: output
      required: true
      description: Output directory to write reports to.
      example: qc/
    # - name: "--output_r2"
    #   type: file
    #   direction: output
    #   required: true
    #   description: Output directory to write reports to.
    #   example: qc/
  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
    - path: ../../../resources_test/cellranger_tiny_fastq/cellranger_tiny_fastq
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: apt
        packages: [ fastqc ]
  - type: nextflow
