name: alignment_quantification
description: |
  Align reads to the genome using STAR and quantify gene expression using
  Salmon

argument_groups:
  - name: Inputs
    arguments:
      - name: --input_fastq1
        type: file
      - name: --input_fastq1
        type: file
      - name: --input_star_index
        type: file
      - name: --input_salmon_index
        type: file
  - name: Outputs
    arguments:
      - name: --output_bam
        type: file
        direction: output
      - name: --output_salmon
        type: file

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run

runners:
  - type: nextflow
