name: alignment_quantification
description: |
  Align reads to the genome using STAR and quantify gene expression using
  Salmon

argument_groups:
  - name: Inputs
    arguments:
      - name: --input_r1
        type: file
        required: true
      - name: --input_r2
        type: file
        required: true
      - name: --input_transcript_fasta
        type: file
        required: true
      - name: --input_gtf
        type: file
        required: true
      - name: --input_star_genome_dir
        type: file
        required: true
  - name: Outputs
    arguments:
      - name: --output_star_bam_genome
        type: file
        direction: output
        default: star/aligned_genome.bam
      - name: --output_star_bam_transcriptome
        type: file
        direction: output
        default: star/aligned_transcriptome.bam
      - name: --output_star_junctions
        type: file
        direction: output
        default: star/splice_junctions.tab
      - name: --output_star_log
        type: file
        direction: output
        default: star/log.out
      - name: --output_salmon
        type: file
        direction: output
        default: salmon

dependencies:
  - name: star/star_align_reads
    repository: biobox
  - name: salmon/salmon_quant
    repository: biobox

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf

runners:
  - type: nextflow
