functionality:
  name: "post_processing"
  namespace: "workflows"
  version: "dev"
  argument_groups:
  - name: "Input"
    arguments:
    - type: "string"
      name: "--id"
      description: "ID of the sample."
      info: null
      example:
      - "foo"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--strandedness"
      description: "Sample strand-specificity. Must be one of unstranded, forward,\
        \ reverse or auto"
      info: null
      default:
      - "auto"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--paired"
      description: "Paired fastq files or not?"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--fasta"
      description: "Path to FASTA genome file."
      info: null
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--fai"
      description: "Path to FASTA index"
      info: null
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--gtf"
      description: "GTF file"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--genome_bam"
      description: "Genome BAM file"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--chrom_sizes"
      description: "File containing chromosome lengths"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--star_multiqc"
      description: "STAR align log file."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--extra_picard_args"
      description: "Extra arguments to pass to picard MarkDuplicates command in addition\
        \ to defaults defined by the pipeline."
      info: null
      default:
      - ""
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--extra_stringtie_args"
      description: "Extra arguments to pass to stringtie command in addition to defaults\
        \ defined by the pipeline."
      info: null
      default:
      - ""
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--stringtie_ignore_gtf"
      description: "Perform reference-guided de novo assembly of transcripts using\
        \ StringTie, i.e. don't restrict to those in GTF file."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--extra_bedtools_args"
      description: "Extra arguments to pass to bedtools genomecov command in addition\
        \ to defaults defined by the pipeline."
      info: null
      default:
      - ""
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--bam_csi_index"
      description: "Create a CSI index for BAM files instead of the traditional BAI\
        \ index. This will be required for genomes with larger chromosome sizes."
      info: null
      default:
      - false
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--min_mapped_reads"
      description: "Minimum percentage of uniquely mapped reads below which samples\
        \ are removed from further processing."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--with_umi"
      description: "Enable UMI-based read deduplication."
      info: null
      default:
      - false
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--skip_qc"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--skip_markdupkicates"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--skip_stringtie"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--skip_bigwig"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Input"
    arguments:
    - type: "file"
      name: "--processed_genome_bam"
      info: null
      default:
      - "$id.markdup.sorted.bam"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--genome_bam_index"
      info: null
      default:
      - "$id.markdup.sorted.bam"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--genome_bam_stats"
      info: null
      default:
      - "$id.markdup.sorted.bam.stats"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--genome_bam_flagstat"
      info: null
      default:
      - "$id.markdup.sorted.bam.flagstat"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--genome_bam_idxstats"
      info: null
      default:
      - "$id.markdup.sorted.bam.idxstats"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--markduplicates_metrics"
      info: null
      default:
      - "$id.markdup.sorted.MarkDuplicates.metrics.txt"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--stringtie_transcript_gtf"
      info: null
      default:
      - "$id.stringtie.transcripts.gtf"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--stringtie_coverage_gtf"
      info: null
      default:
      - "$id.stringtie.coverage.gtf"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--stringtie_abundance"
      info: null
      default:
      - "$id.stringtie.gene_abundance.txt"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--stringtie_ballgown"
      info: null
      default:
      - "$id.stringtie.ballgown"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--bedgraph_forward"
      info: null
      default:
      - "$id.forward.bedgraph"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--bedgraph_reverse"
      info: null
      default:
      - "$id.reverse.bedgraph"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--bigwig_forward"
      info: null
      default:
      - "$id.forward.bigwig"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--bigwig_reverse"
      info: null
      default:
      - "$id.reverse.bigwig"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  description: "A viash sub-workflow for the post-processing stage of nf-core/rnaseq\
    \ pipeline.\n"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  dependencies:
  - name: "picard_markduplicates"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/picard_markduplicates/config.vsh.yaml"
    configInfo:
      functionalityName: "picard_markduplicates"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/picard_markduplicates/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/picard_markduplicates/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/picard_markduplicates"
  - name: "samtools/samtools_sort"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/sort/config.vsh.yaml"
    configInfo:
      functionalityName: "samtools_sort"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/sort/config.vsh.yaml"
      functionalityNamespace: "samtools"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/samtools/samtools_sort/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/samtools/samtools_sort"
  - name: "samtools/samtools_index"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/index/config.vsh.yaml"
    configInfo:
      functionalityName: "samtools_index"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/index/config.vsh.yaml"
      functionalityNamespace: "samtools"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/samtools/samtools_index/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/samtools/samtools_index"
  - name: "samtools/samtools_stats"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/stats/config.vsh.yaml"
    configInfo:
      functionalityName: "samtools_stats"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/stats/config.vsh.yaml"
      functionalityNamespace: "samtools"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/samtools/samtools_stats/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/samtools/samtools_stats"
  - name: "samtools/samtools_flagstat"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/flagstat/config.vsh.yaml"
    configInfo:
      functionalityName: "samtools_flagstat"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/flagstat/config.vsh.yaml"
      functionalityNamespace: "samtools"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/samtools/samtools_flagstat/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/samtools/samtools_flagstat"
  - name: "samtools/samtools_idxstats"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/idxstats/config.vsh.yaml"
    configInfo:
      functionalityName: "samtools_idxstats"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/idxstats/config.vsh.yaml"
      functionalityNamespace: "samtools"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/samtools/samtools_idxstats/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/samtools/samtools_idxstats"
  - name: "stringtie"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/stringtie/config.vsh.yaml"
    configInfo:
      functionalityName: "stringtie"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/stringtie/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/stringtie/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/stringtie"
  - name: "bedtools_genomecov"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/bedtools_genomecov/config.vsh.yaml"
    configInfo:
      functionalityName: "bedtools_genomecov"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/bedtools_genomecov/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/bedtools_genomecov/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/bedtools_genomecov"
  - name: "ucsc/ucsc_bedclip"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/ucsc/bedclip/config.vsh.yaml"
    configInfo:
      functionalityName: "ucsc_bedclip"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/ucsc/bedclip/config.vsh.yaml"
      functionalityNamespace: "ucsc"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/ucsc/ucsc_bedclip/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/ucsc/ucsc_bedclip"
  - name: "ucsc/ucsc_bedgraphtobigwig"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/ucsc/bedgraphtobigwig/config.vsh.yaml"
    configInfo:
      functionalityName: "ucsc_bedgraphtobigwig"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/ucsc/bedgraphtobigwig/config.vsh.yaml"
      functionalityNamespace: "ucsc"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/ucsc/ucsc_bedgraphtobigwig/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/ucsc/ucsc_bedgraphtobigwig"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/workflows/post_processing/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/workflows/post_processing"
  executable: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/workflows/post_processing/main.nf"
  viash_version: "0.8.0-RC5"
  git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
