name: "post_processing"
namespace: "workflows"
version: "main_build"
argument_groups:
- name: "Input"
  arguments:
  - type: "string"
    name: "--id"
    description: "ID of the sample."
    info: null
    example:
    - "foo"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--strandedness"
    description: "Sample strand-specificity. Must be one of unstranded, forward, reverse\
      \ or auto"
    info: null
    default:
    - "auto"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--paired"
    description: "Paired fastq files or not?"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fasta"
    description: "Path to FASTA genome file."
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fai"
    description: "Path to FASTA index"
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--gtf"
    description: "GTF file"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--genome_bam"
    description: "Genome BAM file"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--chrom_sizes"
    description: "File containing chromosome lengths"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--star_multiqc"
    description: "STAR align log file."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--extra_picard_args"
    description: "Extra arguments to pass to picard MarkDuplicates command in addition\
      \ to defaults defined by the pipeline."
    info: null
    default:
    - ""
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--extra_stringtie_args"
    description: "Extra arguments to pass to stringtie command in addition to defaults\
      \ defined by the pipeline."
    info: null
    default:
    - ""
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--stringtie_ignore_gtf"
    description: "Perform reference-guided de novo assembly of transcripts using StringTie,\
      \ i.e. don't restrict to those in GTF file."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--extra_bedtools_args"
    description: "Extra arguments to pass to bedtools genomecov command in addition\
      \ to defaults defined by the pipeline."
    info: null
    default:
    - ""
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--bam_csi_index"
    description: "Create a CSI index for BAM files instead of the traditional BAI\
      \ index. This will be required for genomes with larger chromosome sizes."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--min_mapped_reads"
    description: "Minimum percentage of uniquely mapped reads below which samples\
      \ are removed from further processing."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--with_umi"
    description: "Enable UMI-based read deduplication."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--skip_qc"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--skip_markduplicates"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--skip_stringtie"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--skip_bigwig"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--versions"
    info: null
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Output"
  arguments:
  - type: "file"
    name: "--processed_genome_bam"
    info: null
    default:
    - "$id.markdup.sorted.bam"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--genome_bam_index"
    info: null
    default:
    - "$id.markdup.sorted.bam"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--genome_bam_stats"
    info: null
    default:
    - "$id.markdup.sorted.bam.stats"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--genome_bam_flagstat"
    info: null
    default:
    - "$id.markdup.sorted.bam.flagstat"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--genome_bam_idxstats"
    info: null
    default:
    - "$id.markdup.sorted.bam.idxstats"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--markduplicates_metrics"
    info: null
    default:
    - "$id.markdup.sorted.MarkDuplicates.metrics.txt"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--stringtie_transcript_gtf"
    info: null
    default:
    - "$id.stringtie.transcripts.gtf"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--stringtie_coverage_gtf"
    info: null
    default:
    - "$id.stringtie.coverage.gtf"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--stringtie_abundance"
    info: null
    default:
    - "$id.stringtie.gene_abundance.txt"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--stringtie_ballgown"
    info: null
    default:
    - "$id.stringtie.ballgown"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--bedgraph_forward"
    info: null
    default:
    - "$id.forward.bedgraph"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--bedgraph_reverse"
    info: null
    default:
    - "$id.reverse.bedgraph"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--bigwig_forward"
    info: null
    default:
    - "$id.forward.bigwig"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--bigwig_reverse"
    info: null
    default:
    - "$id.reverse.bigwig"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--updated_versions"
    info: null
    default:
    - "versions.yml"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "nextflow_script"
  path: "main.nf"
  is_executable: true
  entrypoint: "run_wf"
description: "A viash sub-workflow for the post-processing stage of nf-core/rnaseq\
  \ pipeline.\n"
info: null
status: "enabled"
requirements:
  commands:
  - "ps"
dependencies:
- name: "picard_markduplicates"
  repository:
    type: "local"
- name: "samtools/samtools_sort"
  repository:
    type: "local"
- name: "samtools/samtools_index"
  repository:
    type: "local"
- name: "samtools/samtools_stats"
  repository:
    type: "local"
- name: "samtools/samtools_flagstat"
  repository:
    type: "local"
- name: "samtools/samtools_idxstats"
  repository:
    type: "local"
- name: "stringtie"
  repository:
    type: "local"
- name: "bedtools_genomecov"
  repository:
    type: "local"
- name: "ucsc/bedclip"
  repository:
    type: "local"
- name: "ucsc/bedgraphtobigwig"
  repository:
    type: "local"
runners:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
engines:
- type: "native"
  id: "native"
build_info:
  config: "src/workflows/post_processing/config.vsh.yaml"
  runner: "nextflow"
  engine: "native"
  output: "target/nextflow/workflows/post_processing"
  executable: "target/nextflow/workflows/post_processing/main.nf"
  viash_version: "0.9.0-RC2"
  git_commit: "f1bac79d3ebb4bff084f592da4371d1e3a1a6865"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh"
package_config:
  info: null
  viash_version: "0.9.0-RC2"
  source: "src"
  target: "target"
  config_mods:
  - ".version := 'dev'\n.requirements.commands := ['ps']\n.engines[.type == 'docker'].target_registry\
    \ := 'ghcr.io'\n.engines[.type == 'docker'].target_organization := 'data-intuitive'\n\
    .engines[.type == 'docker'].target_image_source := 'https://github.com/data-intuitive/rnaseq.vsh'\n\
    .runners[.type == 'nextflow'].directives.tag := '$id'\n.runners[.type == 'nextflow'].auto.simplifyOutput\
    \ := false"
  - ".version := \"main_build\""
