functionality:
  name: "multiqc"
  info:
    migration_info": 
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/local/multiqc.nf]
      last_sha: 0a1bdcfbb498987643b74e9fccab85ccd9f2a17d
  description: |
    Present QC for raw read, alignment, gene biotype, sample similarity, and strand-specificity checks in a single report.

  argument_groups: 
    - name: "Input"
      arguments:
        - name: "--multiqc_custom_config"
          type: file
        - name: "--multiqc_title"
          type: string
        - name: "--multiqc_methods_description"
          type: file
          default: assets/methods_description_template.yml
        - name: "--mqc_yml"
          type: file
        - name: "--workflow_summary"
          type: file
        - name: "--input"
          type: file
          must_exist: false
        - name: "--versions"
          type: file
          must_exist: false
          
        
    - name: "Ouput"
      arguments:
        - name: "--report"
          type: file
          direction: output
          default: multiqc_report.html
        - name: "--data"
          type: file
          direction: output
          default: multiqc_data
        - name: "--plots"
          type: file
          direction: output
          default: multiqc_plots
        - name: "--updated_versions"
          type: file
          default: versions.yml
          direction: output
      
  resources:
    - type: bash_script
      path: script.sh

  test_resources:
    - type: bash_script
      path: test.sh
    - path: /testData/unit_test_resources/data.zip

platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: apt
        packages: [ pip, unzip ]
      - type: python
        pip: multiqc
  - type: nextflow