functionality:
  name: "star_align"
  namespace: "star"
  version: "dev"
  arguments:
  - type: "boolean"
    name: "--paired"
    description: "Paired fastq files or not?"
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--input"
    description: "Input fastq files."
    info: null
    example:
    - "sample.fastq"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ","
    dest: "par"
  - type: "file"
    name: "--gtf"
    description: "GTF file"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--star_index"
    description: "STAR index directory."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--star_ignore_sjdbgtf"
    description: "When using pre-built STAR indices do not re-extract and use splice\
      \ junctions from the GTF file"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--seq_platform"
    description: "Sequencing platform."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--seq_center"
    description: "sequencing center."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--extra_star_align_args"
    description: "Extra arguments to pass to STAR alignment command in addition to\
      \ defaults defined by the pipeline."
    info: null
    default:
    - ""
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    description: "Path to output directory"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--star_align_bam"
    info: null
    default:
    - "$id.star_aligned.genome.bam"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--star_align_bam_transcriptome"
    info: null
    default:
    - "$id.star_aligned.transcriptome.bam"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--log_final"
    info: null
    default:
    - "$id.star_aligned.log.final.out"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Align reads to a reference genome using STAR\n"
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  info:
    migration_info:
      git_repo: "https://github.com/nf-core/rnaseq.git"
      paths:
      - "modules/nf-core/star/align/main.nf"
      - "modules/nf-core/star/align/meta.yml"
      last_sha: "55398de6ab7577acfe9b1180016a93d7af7eb859"
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ubuntu:22.04"
  target_organization: "data-intuitive"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/data-intuitive/rnaseq.vsh"
  setup:
  - type: "docker"
    run:
    - "apt-get update && \\\napt-get install -y --no-install-recommends ${PACKAGES}\
      \ && \\\nwget --no-check-certificate https://github.com/samtools/samtools/releases/download/1.18/samtools-1.18.tar.bz2\
      \ && \\\ntar -xjf samtools-1.18.tar.bz2 && \\\nrm samtools-1.18.tar.bz2 && \\\
      \ncd samtools-1.18 && \\\n./configure && \\\nmake && \\\nmake install && \\\n\
      cd && \\\nwget --no-check-certificate https://github.com/alexdobin/STAR/archive/refs/tags/2.7.11a.zip\
      \ && \\\nunzip 2.7.11a.zip && \\\ncp STAR-2.7.11a/bin/Linux_x86_64_static/STAR\
      \ /usr/local/bin \n"
    env:
    - "PACKAGES build-essential gcc g++ autoconf automake make wget zlib1g-dev unzip\
      \ perl libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev\
      \ bzip2 gawk"
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/star/align/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/star/star_align"
  executable: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/star/star_align/star_align"
  viash_version: "0.8.0-RC5"
  git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
