name: "rseqc_readdistribution"
namespace: "rseqc"
info:
  migration_info:
    git_repo: https://github.com/nf-core/rnaseq.git
    paths: [modules/nf-core/rseqc/readdistribution/main.nf]
    last_sha: 
description: |
  Calculate how mapped reads are distributed over genomic features.

argument_groups:
- name: "Input"
  arguments: 
  - name: "--input"
    type: file 
    required: true
    description: input alignment file in BAM or SAM format

  - name: "--refgene"
    type: file 
    required: true
    description: Reference gene model in bed format
    
- name: "Output"
  arguments:   
  - name: "--output"
    type: file
    direction: output
    required: false
    default: $id.read_distribution.txt
    description: output file (txt) of read distribution analysis.

resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - path: /testData/unit_test_resources/sarscov2/test.paired_end.sorted.bam
  - path: /testData/unit_test_resources/sarscov2/test.bed12
  
engines:
- type: docker
  image: ubuntu:22.04
  setup:   
    - type: apt
      packages: [ python3-pip ]
    - type: python
      packages: [ RSeQC ]
runners: 
- type: executable
- type: nextflow