name: "prepare_genome"
namespace: "workflows"
version: "main_build"
argument_groups:
- name: "Input"
  arguments:
  - type: "file"
    name: "--fasta"
    description: "Path to FASTA genome file."
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--gtf"
    description: "Path to GTF annotation file. This parameter is *mandatory* if --genome\
      \ is not specified."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--gff"
    description: "Path to GFF3 annotation file. Required if \"--gtf\" is not specified."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--additional_fasta"
    description: "FASTA file to concatenate to genome FASTA file e.g. containing spike-in\
      \ sequences."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--transcript_fasta"
    description: "Path to FASTA transcriptome file."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--gene_bed"
    description: "Path to BED file containing gene intervals. This will be created\
      \ from the GTF file if not specified."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--splicesites"
    description: "Splice sites file required for HISAT2."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--skip_bbsplit"
    description: "Skip BBSplit for removal of non-reference genome reads."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--bbsplit_fasta_list"
    description: "Path to comma-separated file containing a list of reference genomes\
      \ to filter reads against with BBSplit. To use BBSplit, \"--skip_bbsplit\" must\
      \ be explicitly set to \"false\". The file should contain 2 (comma separated)\
      \ columns - short name and full path to reference genome(s)"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--star_index"
    description: "Path to directory or tar.gz archive for pre-built STAR index."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--rsem_index"
    description: "Path to directory or tar.gz archive for pre-built RSEM index."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "extra_rsem_prepare_reference_args"
    description: "Extra arguments to pass to rsem-prepare-reference command in addition\
      \ to defaults defined by the pipeline."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--salmon_index"
    description: "Path to directory or tar.gz archive for pre-built Salmon index."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--kallisto_index"
    description: "Path to directory or tar.gz archive for pre-built Kallisto index."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--hisat2_index"
    description: "Path to directory or tar.gz archive for pre-built HISAT2 index."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--bbsplit_index"
    description: "Path to directory or tar.gz archive for pre-built BBSplit index."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--pseudo_aligner_kmer_size"
    description: "Kmer length passed to indexing step of pseudoaligners."
    info: null
    default:
    - 31
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--gencode"
    description: "Specify if the GTF annotation is in GENCODE format."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--biotype"
    description: "Biotype value to use while appending entries to GTF file when additional\
      \ fasta file is provided."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--filter_gtf"
    description: "Whether to filter the GTF or not?"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--versions"
    info: null
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Output"
  arguments:
  - type: "file"
    name: "--fasta_uncompressed"
    info: null
    default:
    - "reference_genome.fasta"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--gtf_uncompressed"
    info: null
    default:
    - "gene_annotation.gtf"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--transcript_fasta_uncompressed"
    info: null
    default:
    - "transcriptome.fasta"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--gene_bed_uncompressed"
    info: null
    default:
    - "gene_annotation.bed"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--star_index_uncompressed"
    description: "Path to STAR index."
    info: null
    default:
    - "STAR_index"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--rsem_index_uncompressed"
    description: "Path to directory or tar.gz archive for pre-built RSEM index."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--salmon_index_uncompressed"
    description: "Path to Salmon index."
    info: null
    default:
    - "Salmon_index"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--kallisto_index_uncompressed"
    description: "Path to Salmon index."
    info: null
    default:
    - "Kallisto_index"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--bbsplit_index_uncompressed"
    description: "Path to BBSplit index."
    info: null
    default:
    - "BBSplit_index"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--chrom_sizes"
    description: "File containing chromosome lengths"
    info: null
    default:
    - "reference_genome.fasta.sizes"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fai"
    description: "FASTA index file"
    info: null
    default:
    - "reference_genome.fasta.fai"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--updated_versions"
    info: null
    default:
    - "versions.yml"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "nextflow_script"
  path: "main.nf"
  is_executable: true
  entrypoint: "run_wf"
description: "A subworkflow for preparing all the required genome references\n"
info: null
status: "enabled"
requirements:
  commands:
  - "ps"
dependencies:
- name: "gunzip"
  repository:
    type: "local"
- name: "gffread"
  repository:
    type: "local"
- name: "cat_additional_fasta"
  repository:
    type: "local"
- name: "gtf2bed"
  repository:
    type: "local"
- name: "preprocess_transcripts_fasta"
  repository:
    type: "local"
- name: "gtf_filter"
  repository:
    type: "local"
- name: "rsem/rsem_prepare_reference"
  repository:
    type: "local"
- name: "getchromsizes"
  repository:
    type: "local"
- name: "untar"
  repository:
    type: "local"
- name: "star/star_genomegenerate"
  repository:
    type: "local"
- name: "bbmap_bbsplit"
  repository:
    type: "local"
- name: "salmon/salmon_index"
  repository:
    type: "local"
- name: "kallisto/kallisto_index"
  repository:
    type: "local"
runners:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
engines:
- type: "native"
  id: "native"
build_info:
  config: "src/workflows/prepare_genome/config.vsh.yaml"
  runner: "nextflow"
  engine: "native"
  output: "target/nextflow/workflows/prepare_genome"
  executable: "target/nextflow/workflows/prepare_genome/main.nf"
  viash_version: "0.9.0-RC2"
  git_commit: "f1bac79d3ebb4bff084f592da4371d1e3a1a6865"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh"
package_config:
  info: null
  viash_version: "0.9.0-RC2"
  source: "src"
  target: "target"
  config_mods:
  - ".version := 'dev'\n.requirements.commands := ['ps']\n.engines[.type == 'docker'].target_registry\
    \ := 'ghcr.io'\n.engines[.type == 'docker'].target_organization := 'data-intuitive'\n\
    .engines[.type == 'docker'].target_image_source := 'https://github.com/data-intuitive/rnaseq.vsh'\n\
    .runners[.type == 'nextflow'].directives.tag := '$id'\n.runners[.type == 'nextflow'].auto.simplifyOutput\
    \ := false"
  - ".version := \"main_build\""
