functionality:
  name: "prepare_genome"
  namespace: "workflows"
  version: "dev"
  argument_groups:
  - name: "Input"
    arguments:
    - type: "file"
      name: "--fasta"
      description: "Path to FASTA genome file."
      info: null
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--gtf"
      description: "Path to GTF annotation file. This parameter is *mandatory* if\
        \ --genome is not specified."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--gff"
      description: "Path to GFF3 annotation file. Required if \"--gtf\" is not specified."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--additional_fasta"
      description: "FASTA file to concatenate to genome FASTA file e.g. containing\
        \ spike-in sequences."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--transcript_fasta"
      description: "Path to FASTA transcriptome file."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--gene_bed"
      description: "Path to BED file containing gene intervals. This will be created\
        \ from the GTF file if not specified."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--splicesites"
      description: "Splice sites file required for HISAT2."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--skip_bbsplit"
      description: "Skip BBSplit for removal of non-reference genome reads."
      info: null
      default:
      - true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--bbsplit_fasta_list"
      description: "Path to comma-separated file containing a list of reference genomes\
        \ to filter reads against with BBSplit. To use BBSplit, \"--skip_bbsplit\"\
        \ must be explicitly set to \"false\". The file should contain 2 (comma separated)\
        \ columns - short name and full path to reference genome(s)"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--star_index"
      description: "Path to directory or tar.gz archive for pre-built STAR index."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--rsem_index"
      description: "Path to directory or tar.gz archive for pre-built RSEM index."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--salmon_index"
      description: "Path to directory or tar.gz archive for pre-built Salmon index."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--hisat2_index"
      description: "Path to directory or tar.gz archive for pre-built HISAT2 index."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--bbsplit_index"
      description: "Path to directory or tar.gz archive for pre-built BBSplit index."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--gencode"
      description: "Specify if the GTF annotation is in GENCODE format."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--biotype"
      description: "Biotype value to use while appending entries to GTF file when\
        \ additional fasta file is provided."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Output"
    arguments:
    - type: "file"
      name: "--fasta_uncompressed"
      info: null
      default:
      - "reference_genome.fasta"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--gtf_uncompressed"
      info: null
      default:
      - "gene_annotation.gtf"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--transcript_fasta_uncompressed"
      info: null
      default:
      - "transcriptome.fasta"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--gene_bed_uncompressed"
      info: null
      default:
      - "gene_annotation.bed"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--star_index_uncompressed"
      description: "Path to STAR index."
      info: null
      default:
      - "star_index"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--salmon_index_uncompressed"
      description: "Path to Salmon index."
      info: null
      default:
      - "salmon_index"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--bbsplit_index_uncompressed"
      description: "Path to BBSplit index."
      info: null
      default:
      - "bbsplit_index"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--chrom_sizes"
      description: "File containing chromosome lengths"
      info: null
      default:
      - "reference_genome.fasta.sizes"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--fai"
      description: "FASTA index file"
      info: null
      default:
      - "reference_genome.fasta.fai"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  description: "A subworkflow for preparing all the required genome references\n"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  dependencies:
  - name: "gunzip"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/gunzip/config.vsh.yaml"
    configInfo:
      functionalityName: "gunzip"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/gunzip/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/gunzip/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/gunzip"
  - name: "gffread"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/gffread/config.vsh.yaml"
    configInfo:
      functionalityName: "gffread"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/gffread/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/gffread/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/gffread"
  - name: "cat_additional_fasta"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/cat_additional_fasta/config.vsh.yaml"
    configInfo:
      functionalityName: "cat_additional_fasta"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/cat_additional_fasta/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/cat_additional_fasta/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/cat_additional_fasta"
  - name: "gtf2bed"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/gtf2bed/config.vsh.yaml"
    configInfo:
      functionalityName: "gtf2bed"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/gtf2bed/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/gtf2bed/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/gtf2bed"
  - name: "preprocess_transcripts_fasta"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/preprocess_transcripts_fasta/config.vsh.yaml"
    configInfo:
      functionalityName: "preprocess_transcripts_fasta"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/preprocess_transcripts_fasta/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/preprocess_transcripts_fasta/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/preprocess_transcripts_fasta"
  - name: "gtf_gene_filter"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/gtf_gene_filter/config.vsh.yaml"
    configInfo:
      functionalityName: "gtf_gene_filter"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/gtf_gene_filter/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/gtf_gene_filter/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/gtf_gene_filter"
  - name: "rsem/rsem_prepare_reference"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/rsem/prepare_reference/config.vsh.yaml"
    configInfo:
      functionalityName: "rsem_prepare_reference"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/rsem/prepare_reference/config.vsh.yaml"
      functionalityNamespace: "rsem"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/rsem/rsem_prepare_reference/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/rsem/rsem_prepare_reference"
  - name: "getchromsizes"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/getchromsizes/config.vsh.yaml"
    configInfo:
      functionalityName: "getchromsizes"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/getchromsizes/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/getchromsizes/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/getchromsizes"
  - name: "untar"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/untar/config.vsh.yaml"
    configInfo:
      functionalityName: "untar"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/untar/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/untar/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/untar"
  - name: "star/star_genomegenerate"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/star/genomegenerate/config.vsh.yaml"
    configInfo:
      functionalityName: "star_genomegenerate"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/star/genomegenerate/config.vsh.yaml"
      functionalityNamespace: "star"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/star/star_genomegenerate/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/star/star_genomegenerate"
  - name: "bbmap_bbsplit"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/bbmap_bbsplit/config.vsh.yaml"
    configInfo:
      functionalityName: "bbmap_bbsplit"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/bbmap_bbsplit/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/bbmap_bbsplit/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/bbmap_bbsplit"
  - name: "salmon/salmon_index"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/salmon/index/config.vsh.yaml"
    configInfo:
      functionalityName: "salmon_index"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/salmon/index/config.vsh.yaml"
      functionalityNamespace: "salmon"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/salmon/salmon_index/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/salmon/salmon_index"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/workflows/prepare_genome/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/workflows/prepare_genome"
  executable: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/workflows/prepare_genome/main.nf"
  viash_version: "0.8.0-RC5"
  git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
