functionality:
  name: "dupradar"
  version: "dev"
  arguments:
  - type: "string"
    name: "--id"
    description: "Sample ID"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--input"
    description: "path to input alignment file in BAM format"
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--gtf_annotation"
    description: "path to GTF annotation file."
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--paired"
    description: "add flag if input alignment file consists of paired reads"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--strandedness"
    description: "strandedness of input bam file reads (forward, reverse or unstranded\
      \ (default, applicable to paired reads))"
    info: null
    required: false
    choices:
    - "forward"
    - "reverse"
    - "unstranded"
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_dupmatrix"
    description: "path to output file (txt) of duplicate tag counts"
    info: null
    default:
    - "$id.dup_matrix.txt"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_dup_intercept_mqc"
    description: "path to output file (txt) of multiqc intercept value DupRadar"
    info: null
    default:
    - "$id.dup_intercept_mqc.txt"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_duprate_exp_boxplot"
    description: "path to output file (pdf) of distribution of expression box plot"
    info: null
    default:
    - "$id.duprate_exp_boxplot.pdf"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_duprate_exp_densplot"
    description: "path to output file (pdf) of 2D density scatter plot of duplicate\
      \ tag counts"
    info: null
    default:
    - "$id.duprate_exp_densityplot.pdf"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_duprate_exp_denscurve_mqc"
    description: "path to output file (pdf) of density curve of gene duplication multiqc"
    info: null
    default:
    - "$id.duprate_exp_density_curve_mqc.pdf"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_expression_histogram"
    description: "path to output file (pdf) of distribution of RPK values per gene\
      \ histogram"
    info: null
    default:
    - "$id.expression_hist.pdf"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_intercept_slope"
    description: "output file (txt) with progression of duplication rate value"
    info: null
    default:
    - "$id.intercept_slope.txt"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  - type: "file"
    path: "dupradar.r"
  description: "Assessment of duplication rates in RNA-Seq datasets\n"
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  - type: "file"
    path: "testData/minimal_test/SRR6357070.bam"
  - type: "file"
    path: "testData/reference/genes.gtf.gz"
  info:
    migration_info:
      git_repo: "https://github.com/nf-core/rnaseq.git"
      paths:
      - "modules/local/dupradar.nf"
      last_sha: "54721c6946daf6d602d7069dc127deef9cbe6b33"
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ubuntu:22.04"
  target_organization: "data-intuitive"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/data-intuitive/rnaseq.vsh"
  setup:
  - type: "apt"
    packages:
    - "r-base"
    interactive: false
  - type: "r"
    bioc:
    - "dupRadar"
    bioc_force_install: false
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/dupradar/config.vsh.yaml"
  platform: "docker"
  output: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/docker/dupradar"
  executable: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/docker/dupradar/dupradar"
  viash_version: "0.8.0-RC5"
  git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
