functionality:
  name: "rseqc_junctionannotation"
  namespace: "rseqc"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/nf-core/rseqc/junctionannotation/main.nf]
      last_sha: 
  description: |
    Compare detected splice junctions to reference gene model.

  arguments:
    - name: "--input"
      type: file 
      required: true
      description: input alignment file in BAM or SAM format

    - name: "--refgene"
      type: file 
      required: true
      description: Reference gene model in bed format

    - name: "--map_qual"
      type: integer
      required: false
      default: 30 
      description: Minimum mapping quality (phred scaled) to determine uniquely mapped reads, default=30.
      min: 0

    - name: "--min_intron"
      type: integer
      required: false
      default: 50
      min: 1 
      description: Minimum intron length (bp), default = 50.
   
    - name: "--output_log"
      type: file
      direction: output
      required: false
      default: $id.junction_annotation.log
      description: output log of junction annotation script

    - name: "--output_plot_r"
      type: file
      direction: output
      required: false
      default: $id.junction_annotation_plot.r
      description: r script to generate splice_junction and splice_events plot

    - name: "--output_junction_bed"
      type: file
      direction: output
      required: false
      default: $id.junction_annotation.bed
      description: junction annotation file (bed format)

    - name: "--output_junction_interact"
      type: file
      direction: output
      required: false
      default: $id.junction_annotation.Interact.bed
      description: interact file (bed format) of junctions. Can be uploaded to UCSC genome browser or converted to bigInteract (using bedToBigBed program) for visualization.

    - name: "--output_junction_sheet"
      type: file
      direction: output
      required: false
      default: $id.junction_annotation.xls
      description: junction annotation file (xls format)

    - name: "--output_splice_events_plot"
      type: file
      direction: output
      required: false
      default: $id.splice_events.pdf
      description: plot of splice events (pdf)

    - name: "--output_splice_junctions_plot"
      type: file
      direction: output
      required: false
      default: $id.splice_junctions_plot.pdf
      description: plot of junctions (pdf)

  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
    - path: /testData/test/SRR6357070.bam
    - path: /testData/test/genome_gfp.bed
   
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:   
      - type: apt
        packages: [ python3-pip, r-base]
      - type: python
        packages: [ RSeQC ]
  - type: nextflow