name: "subread_featurecounts"
version: "main_build"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "boolean"
    name: "--paired"
    description: "Paired-end read?"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--strandedness"
    description: "Sample strand-specificity"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--bam"
    description: "BAM file containing read alignments"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--gtf"
    description: "Genomic features annotation in GTF"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--extra_featurecounts_args"
    description: "Extra arguments to pass to featureCounts command in addition to\
      \ defaults defined by the pipeline"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--featurecounts_group_type"
    description: "The attribute type used to group feature types in the GTF file when\
      \ generating the biotype plot with featureCounts."
    info: null
    default:
    - "gene_biotype"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--featurecounts_feature_type"
    description: "By default, the pipeline assigns reads based on the 'exon' attribute\
      \ within the GTF file."
    info: null
    default:
    - "exon"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--gencode"
    description: "Specify if the GTF annotation is in GENCODE format."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--versions"
    info: null
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--counts"
    description: "Counts of reads mapping to features"
    info: null
    default:
    - "$id.featureCounts.txt"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--summary"
    description: "Summary log file"
    info: null
    default:
    - "$id.featureCounts.txt.summary"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--updated_versions"
    info: null
    default:
    - "versions.yml"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "bash_script"
  path: "script.sh"
  is_executable: true
description: "Count reads that map to genomic features"
test_resources:
- type: "bash_script"
  path: "test.sh"
  is_executable: true
- type: "file"
  path: "testData/unit_test_resources/wgEncodeCaltechRnaSeqGm12878R1x75dAlignsRep2V2.bam"
- type: "file"
  path: "testData/unit_test_resources/genes.gtf"
info:
  migration_info:
    git_repo: "https://github.com/nf-core/rnaseq.git"
    paths:
    - "modules/nf-core/subread/featurecounts/main.nf"
    - "modules/nf-core/subread/featurecounts/meta.yml"
    last_sha: "54721c6946daf6d602d7069dc127deef9cbe6b33"
status: "enabled"
requirements:
  commands:
  - "ps"
runners:
- type: "executable"
  id: "docker"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "ubuntu:22.04"
  target_organization: "data-intuitive"
  target_registry: "ghcr.io"
  target_tag: "main_build"
  namespace_separator: "/"
  target_image_source: "https://github.com/data-intuitive/rnaseq.vsh"
  setup:
  - type: "apt"
    packages:
    - "subread"
    interactive: false
  entrypoint: null
  cmd: null
build_info:
  config: "src/subread_featurecounts/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/subread_featurecounts"
  executable: "target/nextflow/subread_featurecounts/subread_featurecounts"
  viash_version: "0.9.0-RC2"
  git_commit: "f1bac79d3ebb4bff084f592da4371d1e3a1a6865"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh"
package_config:
  info: null
  viash_version: "0.9.0-RC2"
  source: "src"
  target: "target"
  config_mods:
  - ".version := 'dev'\n.requirements.commands := ['ps']\n.engines[.type == 'docker'].target_registry\
    \ := 'ghcr.io'\n.engines[.type == 'docker'].target_organization := 'data-intuitive'\n\
    .engines[.type == 'docker'].target_image_source := 'https://github.com/data-intuitive/rnaseq.vsh'\n\
    .runners[.type == 'nextflow'].directives.tag := '$id'\n.runners[.type == 'nextflow'].auto.simplifyOutput\
    \ := false"
  - ".version := \"main_build\""
  - ".engines[.type == 'docker'].target_tag := 'main_build'"
