name: "sortmerna"
info:
  migration_info:
    git_repo: https://github.com/nf-core/rnaseq.git
    paths: [modules/nf-core/sortmerna/main.nf, modules/nf-core/sortmerna/meta.yml]
    last_sha: 54721c6946daf6d602d7069dc127deef9cbe6b33
description: | 
  Local sequence alignment tool for filtering, mapping and clustering. The main application of SortMeRNA is filtering rRNA from metatranscriptomic data. SortMeRNA takes as input files of reads (fasta, fastq, fasta.gz, fastq.gz) and one or multiple rRNA database file(s), and sorts apart aligned and rejected reads into two files.

argument_groups:
- name: "Input"
  arguments: 
  - name: "--paired"
    type: boolean
    description: Are the reads single-end or paired-end
  - name: "--input"
    type: file
    multiple: true
    multiple_sep: ","
    description: Input fastq
  - name: "--ribo_database_manifest"
    type: file
    multiple: true
    description: Text file containing paths to fasta files (one per line) that will be used to create the database for SortMeRNA.

- name: "Output"
  arguments:     
  - name: "--sortmerna_log"
    type: file
    direction: output
    default: $id.sortmerna.log
    required: false
    must_exist: false
    description: Sortmerna log file.
  - name: "--fastq_1"
    type: file
    required: true
    description: Output file for read 1.
    direction: output
    default: $id.$key.read_1.fastq.gz
  - name: "--fastq_2"
    type: file
    required: false
    must_exist: false
    description: Output file for read 2.
    direction: output
    default: $id.$key.read_2.fastq.gz

resources:
  - type: bash_script
    path: script.sh

test_resources:
  - type: bash_script
    path: test.sh
  - path: /testData/minimal_test/input_fastq/SRR6357070_1.fastq.gz
  - path: /testData/minimal_test/input_fastq/SRR6357070_2.fastq.gz
  - path: /testData/minimal_test/reference/rRNA
  
engines:
- type: docker
  image: quay.io/biocontainers/sortmerna:4.3.6--h9ee0642_0
runners: 
- type: executable
- type: nextflow 
