functionality:
  name: "infer_strandedness"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [lib/WorkflowRnaseq.groovy]
      last_sha: 993fff67ba7590c85cb107143513943ff39dbd21
  description: Get Salmon inferred strandedness

  arguments: 
    - name: "--json"
      type: file
      description: File containing meta information from Salmon quant
    
    - name: "--strandedness"
      type: string
      direction: output
      description: Strandedness inferred by Salmon quant
  
  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: python:latest
    setup:
      - type: python
  - type: nextflow