functionality:
  name: salmon_index
  namespace: salmon
  description: | 
    Create Salmon index.
  
  arguments: 
    - name: "--genome_fasta"
      type: file
    - name: "--transcriptome_fasta"
      type: file

    - name: "--salmon_index"
      type: file
      direction: output

  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh

platforms:
  - type: nextflow
  - type: docker
    image: ubuntu:20.04
    setup:
      - type: docker
        env: 
          - SALMON_VERSION 1.10.1
          - PACKAGES git gcc make g++ libboost-all-dev liblzma-dev libbz2-dev ca-certificates zlib1g-dev libcurl4-openssl-dev curl unzip autoconf apt-transport-https ca-certificates gnupg software-properties-common wget
        run: |
          apt-get update && \
          apt remove -y libcurl4 && \
          apt-get install -y --no-install-recommends ${PACKAGES} && \
          apt-get clean && \
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add - && \
          apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' && \
          apt-get update && \
          apt-key --keyring /etc/apt/trusted.gpg del C1F34CDD40CD72DA && \
          apt-get install kitware-archive-keyring && \
          apt-get install -y cmake && \
          curl -k -L https://github.com/COMBINE-lab/salmon/archive/v${SALMON_VERSION}.tar.gz -o salmon-v${SALMON_VERSION}.tar.gz && \
          tar xzf salmon-v${SALMON_VERSION}.tar.gz && \
          cd salmon-${SALMON_VERSION} && \
          mkdir build && \
          cd build && \
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/salmon && make && make install && \
          apt-get update && \
          apt-get install -y --no-install-recommends libhwloc5 && \
          rm -rf /var/lib/apt/lists/* && \
          cp /usr/local/salmon/ /usr/local/

        # apt-get update && \
        # apt-get install -y --no-install-recommends git gcc make g++ libboost-all-dev liblzma-dev libbz2-dev ca-certificates zlib1g-dev libcurl4-openssl-dev curl unzip autoconf apt-transport-https ca-certificates gnupg software-properties-common wget cmake && \
        # apt-get clean && \
        # wget --no-check-certificate https://github.com/COMBINE-lab/salmon/archive/refs/tags/v1.10.1.tar.gz && \
        # tar xzf v1.10.1.tar.gz && \
        # cd salmon-1.10.1 && \
        # mkdir build && \
        # cd build && \
        # cmake .. && make && make install
