functionality:
  name: salmon_index
  namespace: salmon
  description: | 
    Create Salmon index.
  
  arguments: 
    - name: "--genome_fasta"
      type: file
    - name: "--transcriptome_fasta"
      type: file

    - name: "--salmon_index"
      type: file
      direction: output

  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh

platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: docker
        env: 
          - SALMON_VERSION 1.10.1
          - TZ Europe/Brussels
          - PACKAGES git gcc make g++ libboost-all-dev liblzma-dev libbz2-dev ca-certificates zlib1g-dev libcurl4-openssl-dev curl unzip autoconf apt-transport-https ca-certificates gnupg software-properties-common wget tar 
        run: |
          ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
          apt-get update && \
          apt remove -y libcurl4 && \
          apt-get install -y --no-install-recommends ${PACKAGES} && \
          apt-get clean && \
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add - && \
          apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' && \
          apt-get update && \
          apt-key --keyring /etc/apt/trusted.gpg del C1F34CDD40CD72DA && \
          apt-get install kitware-archive-keyring && \
          apt-get install -y cmake && \
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb && \
          dpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb && \
          curl -k -L https://github.com/COMBINE-lab/salmon/archive/v${SALMON_VERSION}.tar.gz -o salmon-v${SALMON_VERSION}.tar.gz && \
          tar xzf salmon-v${SALMON_VERSION}.tar.gz && \
          cd salmon-${SALMON_VERSION} && \
          mkdir build && \
          cd build && \
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/salmon && make && make install && \
          cd && apt-get update && \
          apt-get install -y --no-install-recommends libhwloc5 && \
          rm -rf /var/lib/apt/lists/* && \
          echo "export PATH=/usr/local/salmon/bin:${PATH}" > /etc/environment && \
          echo "export LD_LIBRARY_PATH=/usr/local/salmon/lib:${LD_LIBRARY_PATH}" > /etc/environment
        # run: | 
        #   ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
        #   apt-get update && \
        #   apt-get install -y --no-install-recommends ${PACKAGES} && \
        #   apt-get clean && \
        #   wget --no-check-certificate https://github.com/COMBINE-lab/salmon/releases/download/v1.10.0/salmon-1.10.0_linux_x86_64.tar.gz && \
        #   tar xzf salmon-1.10.0_linux_x86_64.tar.gz && \
        #   cp salmon-latest_linux_x86_64/bin/salmon /usr/bin 
  - type: nextflow  
