functionality:
  name: "subread_featurecounts"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/nf-core/subread/featurecounts/main.nf, modules/nf-core/subread/featurecounts/meta.yml]
      last_sha: 54721c6946daf6d602d7069dc127deef9cbe6b33
  description: Count reads that map to genomic features

  arguments: 
    - name: "--paired"
      type: boolean
      description: Paired-end read?
    - name: "--strandedness"
      type: string
      description: Sample strand-specificity
    - name: "--bam"
      type: file
      description: BAM file containing read alignments
    - name: "--gtf"
      type: file
      description: Genomic features annotation in GTF
    - name: "--extra_featurecounts_args"
      type: string
      description: Extra arguments to pass to featureCounts command in addition to defaults defined by the pipeline
    - name: "--featurecounts_group_type"
      type: string
      description: The attribute type used to group feature types in the GTF file when generating the biotype plot with featureCounts.
      default: gene_biotype
    - name: "--featurecounts_feature_type"
      type: string
      description: By default, the pipeline assigns reads based on the 'exon' attribute within the GTF file.
      default: exon
    - name: "--gencode"
      type: boolean
      description: Specify if the GTF annotation is in GENCODE format.

    - name: "--counts"
      type: file
      direction: output
      description: Counts of reads mapping to features
      default: $id.featureCounts.txt
    - name: "--summary"
      type: file
      direction: output
      description: Summary log file
      default: $id.featureCounts.txt.summary

  resources:
    - type: bash_script
      path: script.sh
  
  test_resources: 
    - type: bash_script
      path: test.sh
    - path: testData/reference/genes.gtf.gz
    - path: testData/minimal_test/test.bam  # add test BAM file
    
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: apt
        packages:
          - subread
  - type: nextflow