functionality:
  name: "salmon_quant_merge_counts"
  namespace: "workflows"
  version: "dev"
  argument_groups:
  - name: "Input"
    arguments:
    - type: "file"
      name: "--salmon_quant_results"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ","
      dest: "par"
    - type: "file"
      name: "--gtf"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--gtf_extra_attributes"
      info: null
      default:
      - "gene_name"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--gtf_group_features"
      info: null
      default:
      - "gene_id"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Output"
    arguments:
    - type: "file"
      name: "--tpm_gene"
      info: null
      default:
      - "salmon.merged.gene_tpm.tsv"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--counts_gene"
      info: null
      default:
      - "salmon.merged.gene_counts.tsv"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--counts_gene_length_scaled"
      info: null
      default:
      - "salmon.merged.gene_counts_length_scaled.tsv"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--counts_gene_scaled"
      info: null
      default:
      - "salmon.merged.gene_counts_scaled.tsv"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--tpm_transcript"
      info: null
      default:
      - "salmon.merged.transcript_tpm.tsv"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--counts_transcript"
      info: null
      default:
      - "salmon.merged.transcript_counts.tsv"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--salmon_merged_summarizedexperiment"
      info: null
      default:
      - "salmon_merged_summarizedexperiment"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  description: "A sub-workflow to merge the counts obtained from salmon quant across\
    \ all samples."
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  dependencies:
  - name: "salmon/salmon_tx2gene"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/salmon/tx2gene/config.vsh.yaml"
    configInfo:
      functionalityName: "salmon_tx2gene"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/salmon/tx2gene/config.vsh.yaml"
      functionalityNamespace: "salmon"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/salmon/salmon_tx2gene/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/salmon/salmon_tx2gene"
  - name: "salmon/salmon_tximport"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/salmon/tximport/config.vsh.yaml"
    configInfo:
      functionalityName: "salmon_tximport"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/salmon/tximport/config.vsh.yaml"
      functionalityNamespace: "salmon"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/salmon/salmon_tximport/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/salmon/salmon_tximport"
  - name: "salmon/salmon_summarizedexperiment"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/salmon/summarizedexperiment/config.vsh.yaml"
    configInfo:
      functionalityName: "salmon_summarizedexperiment"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/salmon/summarizedexperiment/config.vsh.yaml"
      functionalityNamespace: "salmon"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/salmon/salmon_summarizedexperiment/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/salmon/salmon_summarizedexperiment"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/workflows/salmon_quant_merge_counts/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/workflows/salmon_quant_merge_counts"
  executable: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/workflows/salmon_quant_merge_counts/main.nf"
  viash_version: "0.8.0-RC5"
  git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
