name: "rsem_prepare_reference"
namespace: "rsem"
version: "main_build"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--fasta"
    description: "Genome fasta file"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--gtf"
    description: "GTF file"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--star"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--versions"
    info: null
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--rsem"
    description: "RSEM index directory."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--transcript_fasta"
    description: "Fasta file of transcripts"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--updated_versions"
    info: null
    default:
    - "versions.yml"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "bash_script"
  path: "script.sh"
  is_executable: true
description: "Prepare a reference genome for RSEM.\n"
test_resources:
- type: "bash_script"
  path: "test.sh"
  is_executable: true
- type: "file"
  path: "testData/minimal_test/reference/genome.fasta"
- type: "file"
  path: "testData/minimal_test/reference/genes.gtf.gz"
info:
  migration_info:
    git_repo: "https://github.com/nf-core/rnaseq.git"
    paths:
    - "modules/nf-core/rsem/preparereference/main.nf"
    - "modules/nf-core/rsem/preparereference/meta.yml"
    last_sha: "92b2a7857de1dda9d1c19a088941fc81e2976ff7"
status: "enabled"
requirements:
  commands:
  - "ps"
runners:
- type: "executable"
  id: "docker"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "ubuntu:22.04"
  target_organization: "data-intuitive"
  target_registry: "ghcr.io"
  target_tag: "main_build"
  namespace_separator: "/"
  target_image_source: "https://github.com/data-intuitive/rnaseq.vsh"
  setup:
  - type: "docker"
    run:
    - "apt-get update && \\\napt-get install -y --no-install-recommends build-essential\
      \ gcc g++ make wget zlib1g-dev unzip && \\\napt-get clean && \\\nwget --no-check-certificate\
      \ https://github.com/alexdobin/STAR/archive/refs/tags/2.7.11a.zip && \\\nunzip\
      \ 2.7.11a.zip && \\\ncp STAR-2.7.11a/bin/Linux_x86_64_static/STAR /usr/local/bin\
      \  && \\\ncd && \\\nwget --no-check-certificate https://github.com/deweylab/RSEM/archive/refs/tags/v1.3.3.zip\
      \ && \\\nunzip v1.3.3.zip && \\\ncd RSEM-1.3.3 && \\\nmake && \\\nmake install\n"
  entrypoint: null
  cmd: null
build_info:
  config: "src/rsem/rsem_prepare_reference/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/rsem/rsem_prepare_reference"
  executable: "target/nextflow/rsem/rsem_prepare_reference/rsem_prepare_reference"
  viash_version: "0.9.0-RC2"
  git_commit: "f1bac79d3ebb4bff084f592da4371d1e3a1a6865"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh"
package_config:
  info: null
  viash_version: "0.9.0-RC2"
  source: "src"
  target: "target"
  config_mods:
  - ".version := 'dev'\n.requirements.commands := ['ps']\n.engines[.type == 'docker'].target_registry\
    \ := 'ghcr.io'\n.engines[.type == 'docker'].target_organization := 'data-intuitive'\n\
    .engines[.type == 'docker'].target_image_source := 'https://github.com/data-intuitive/rnaseq.vsh'\n\
    .runners[.type == 'nextflow'].directives.tag := '$id'\n.runners[.type == 'nextflow'].auto.simplifyOutput\
    \ := false"
  - ".version := \"main_build\""
  - ".engines[.type == 'docker'].target_tag := 'main_build'"
