functionality:
  name: "rseqc_tin"
  namespace: "rseqc"
  version: "dev"
  arguments:
  - type: "file"
    name: "--bam_input"
    description: "Path to input alignment file in BAM or SAM format."
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--bai_input"
    description: "Path to bam index file in bai format."
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--refgene"
    description: "BED file containing the reference gene model"
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--minimum_coverage"
    description: "Minimum number of reads mapped to a transcript, default = 10."
    info: null
    default:
    - 10
    required: false
    min: 1
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--sample_size"
    description: "Number of equal-spaced nucleotide positions picked from mRNA. Note,\
      \ if this number is larger than the length of mRNA (L), it will be halved until\
      \ it's smaller than L (default = 100)"
    info: null
    default:
    - 100
    required: false
    min: 1
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean_true"
    name: "--subtract_background"
    description: "Set flag to subtract background noise (estimated from intronic reads).\
      \ Only use this option if there are substantial intronic reads."
    info: null
    direction: "input"
    dest: "par"
  - type: "file"
    name: "--output_tin_summary"
    description: "summary statistics (txt) of calculated TIN metrics"
    info: null
    default:
    - "$id.tin_summary.txt"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_tin"
    description: "file with TIN metrics (xls)"
    info: null
    default:
    - "$id.tin.xls"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Calculte TIN (transcript integrity number) from RNA-seq reads\n"
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  - type: "file"
    path: "testData/minimal_test/SRR6357070.bam"
  - type: "file"
    path: "testData/minimal_test/SRR6357070.bam.bai"
  - type: "file"
    path: "testData/minimal_test/genome_gfp.bed"
  info:
    migration_info:
      git_repo: "https://github.com/nf-core/rnaseq.git"
      paths:
      - "modules/nf-core/rseqc/tin/main.nf"
      last_sha: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ubuntu:22.04"
  target_organization: "data-intuitive"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/data-intuitive/rnaseq.vsh"
  setup:
  - type: "apt"
    packages:
    - "python3-pip"
    interactive: false
  - type: "docker"
    run:
    - "pip3 install RSeQC\n"
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/rseqc/tin/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/rseqc/rseqc_tin"
  executable: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/rseqc/rseqc_tin/rseqc_tin"
  viash_version: "0.8.0-RC5"
  git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
