functionality:
  name: "preprocess_transcripts_fasta"
  info:
    migration_info:
      git_repo: https://github.com/nf-core/rnaseq.git
      paths: [modules/local/preprocess_transcripts_fasta_gencode.nf]
      last_sha: 0a1bdcfbb498987643b74e9fccab85ccd9f2a17d
  description: |
    Process transcripts FASTA if GTF file is GENOCODE format

  arguments:
    - name: "--transcript_fasta"
      type: file 
      required: true
      description: Path of transcripts FASTA file
    - name: "--versions"
      type: file
      must_exist: false
      
    
    - name: "--output"
      type: file
      direction: output
      required: true
      description: Path of processed output FASTA file.
    - name: "--updated_versions"
      type: file
      default: versions.yml
      direction: output

  resources:
    - type: bash_script
      path: script.sh
  
  test_resources:
    - type: bash_script
      path: test.sh
    - path: /testData/reference/transcriptome.fasta
   
platforms:
  - type: docker
    image: ubuntu:22.04
  - type: nextflow
