name: "bedgraphtobigwig"
namespace: "ucsc"
info:
  migration_info:
    git_repo: https://github.com/nf-core/rnaseq.git
    paths: [modules/nf-core/ucsc/bedgraphtobigwig/main.nf, modules/nf-core/ucsc/bedgraphtobigwig/meta.yml]
    last_sha: 54721c6946daf6d602d7069dc127deef9cbe6b33
description: Convert a bedGraph file to bigWig format

argument_groups:
- name: "Input"
  arguments: 
  - name: "--bedgraph"
    type: file
    description: bedGraph file which should be converted
  - name: "--sizes"
    type: file
    description: File with chromosome sizes
    
- name: "Output"
  arguments: 
  - name: "--bigwig"
    type: file
    direction: output
    description: bigWig coverage file relative to genes on the input file
    default: $id.$key.bigwig

resources:
  - type: bash_script
    path: script.sh

test_resources:
  - type: bash_script
    path: test.sh
  - path: /testData/unit_test_resources/test.bedgraph
  - path: /testData/unit_test_resources/genome.sizes    

engines:
- type: docker
  image: ubuntu:22.04
  setup:
    - type: apt
      packages:
        - rsync
        - libcurl4
    - type: docker
      run: | 
        rsync -aP rsync://hgdownload.soe.ucsc.edu/genome/admin/exe/linux.x86_64/bedGraphToBigWig /usr/local/bin/
runners: 
- type: executable
- type: nextflow