name: "rseqc_bamstat"
namespace: "rseqc"
info:
  migration_info:
    git_repo: https://github.com/nf-core/rnaseq.git
    paths: [modules/nf-core/rseqc/bamstat/main.nf]
    last_sha: 54721c6946daf6d602d7069dc127deef9cbe6b33
description: |
  Generate statistics from a bam file.

argument_groups:
- name: "Input"
  arguments: 
  - name: "--input"
    type: file 
    required: true
    description: input alignment file in BAM or SAM format

  - name: "--map_qual"
    type: integer
    required: false
    default: 30 
    description: Minimum mapping quality (phred scaled) to determine uniquely mapped reads, default=30.
    min: 0
    
- name: "Output"
  arguments: 
  - name: "--output"
    type: file
    direction: output
    required: false
    default: $id.mapping_quality.txt
    description: output file (txt) with mapping quality statistics

resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - path: /testData/unit_test_resources/sarscov2/test.paired_end.sorted.bam
  
engines:
- type: docker
  image: ubuntu:22.04
  setup:   
    - type: apt
      packages: [ python3-pip ]
    - type: python
      packages: [ RSeQC ]
runners: 
- type: executable
- type: nextflow
  directives:
    label: [ midmem, midcpu ]
