name: "cat_fastq"
info:
  migration_info:
    git_repo: https://github.com/nf-core/rnaseq.git
    paths: [modules/nf-core/cat/fastq/main.nf, modules/nf-core/cat/fastq/meta.yml]
    last_sha: 54721c6946daf6d602d7069dc127deef9cbe6b33
description: Concatenate multiple fastq files 

argument_groups:
- name: "Input"
  arguments: 
  - name: "--read_1"
    type: file
    multiple: true
    multiple_sep: ";"
    description: Read 1 fastq files to be concatenated
  - name: "--read_2"
    type: file
    multiple: true
    multiple_sep: ";"
    description: Read 2 fastq files to be concatenated

- name: "Output"
  arguments:   
  - name: "--fastq_1"
    type: file
    direction: output
    default: $id_merged.fastq
    description: Concatenated read 1 fastq
  - name: "--fastq_2"
    type: file
    direction: output
    must_exist: false
    default: $id_merged.fastq
    description: Concatenated read 2 fastq

resources:
  - type: bash_script
    path: script.sh

test_resources:
  - type: bash_script
    path: test.sh
  - path: /testData/minimal_test/input_fastq/SRR6357070_1.fastq.gz 
  - path: /testData/minimal_test/input_fastq/SRR6357071_1.fastq.gz
  - path: /testData/minimal_test/input_fastq/SRR6357070_2.fastq.gz
  - path: /testData/minimal_test/input_fastq/SRR6357071_2.fastq.gz

engines:
  - type: docker
    image: ubuntu:22.04
runners:
  - type: executable
  - type: nextflow