name: "genome_alignment_and_quant"
namespace: "workflows"
version: "main_build"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "string"
    name: "--id"
    description: "ID of the sample."
    info: null
    example:
    - "foo"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fastq_1"
    alternatives:
    - "-i"
    description: "Path to the sample (or read 1 of paired end sample)."
    info: null
    example:
    - "input.fastq.gz"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--fastq_2"
    description: "Path to read 2 of the sample."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--strandedness"
    description: "Sample strand-specificity. Must be one of unstranded, forward, or\
      \ reverse"
    info: null
    required: false
    choices:
    - "forward"
    - "reverse"
    - "unstranded"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--gtf"
    description: "GTF file"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--transcript_fasta"
    description: "Fasta file of the reference transcriptome."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--star_index"
    description: "STAR index directory."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--star_ignore_sjdbgtf"
    description: "When using pre-built STAR indices do not re-extract and use splice\
      \ junctions from the GTF file"
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--seq_platform"
    description: "Sequencing platform."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--seq_center"
    description: "Sequencing center."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--extra_star_align_args"
    description: "Extra arguments to pass to STAR alignment command in addition to\
      \ defaults defined by the pipeline."
    info: null
    default:
    - ""
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--bam_csi_index"
    description: "Create a CSI index for BAM files instead of the traditional BAI\
      \ index. This will be required for genomes with larger chromosome sizes."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--umi_dedup_stats"
    description: "Generate output stats when running \"umi_tools dedup\"."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--with_umi"
    description: "Enable UMI-based read deduplication."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--salmon_quant_libtype"
    description: "Override Salmon library type inferred based on strandedness defined\
      \ in meta object."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--extra_salmon_quant_args"
    description: "Extra arguments to pass to salmon quant command in addition to defaults\
      \ defined by the pipeline."
    info: null
    default:
    - ""
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--gtf_group_features"
    description: "Define the attribute type used to group features in the GTF file\
      \ when running Salmon."
    info: null
    default:
    - "gene_id"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--gtf_extra_attributes"
    description: "By default, the pipeline uses the gene_name field to obtain additional\
      \ gene identifiers from the input GTF file when running Salmon."
    info: null
    default:
    - "gene_name"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "extra_rsem_calculate_expression_args"
    description: "Extra arguments to pass to rsem-calculate-expression command in\
      \ addition to defaults defined by the pipeline."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--versions"
    info: null
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--star_alignment"
    info: null
    default:
    - "$id_STAR"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--star_multiqc"
    info: null
    default:
    - "$id.star_align.log"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--genome_bam_sorted"
    info: null
    default:
    - "$id.genome.bam"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--genome_bam_index"
    info: null
    default:
    - "$id.genome.bam.bai"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--genome_bam_stats"
    info: null
    default:
    - "$id.genome.stats"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--genome_bam_flagstat"
    info: null
    default:
    - "$id.genome.flagstat"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--genome_bam_idxstats"
    info: null
    default:
    - "$id.genome.idxstats"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--transcriptome_bam"
    info: null
    default:
    - "$id.transcriptome.bam"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--transcriptome_bam_index"
    info: null
    default:
    - "$id.transcriptome.bam.bai"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--transcriptome_bam_stats"
    info: null
    default:
    - "$id.transcriptome.stats"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--transcriptome_bam_flagstat"
    info: null
    default:
    - "$id.transcriptome.flagstat"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--transcriptome_bam_idxstats"
    info: null
    default:
    - "$id.transcriptome.idxstats"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--salmon_quant_results"
    info: null
    default:
    - "$id.salmon_quant"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--updated_versions"
    info: null
    default:
    - "versions.yml"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "nextflow_script"
  path: "main.nf"
  is_executable: true
  entrypoint: "run_wf"
description: "A viash sub-workflow for genome alignment and quantification stage of\
  \ nf-core/rnaseq pipeline.\n"
info: null
status: "enabled"
requirements:
  commands:
  - "ps"
dependencies:
- name: "star/star_align"
  repository:
    type: "local"
- name: "samtools/samtools_sort"
  repository:
    type: "local"
- name: "samtools/samtools_index"
  repository:
    type: "local"
- name: "samtools/samtools_stats"
  repository:
    type: "local"
- name: "samtools/samtools_flagstat"
  repository:
    type: "local"
- name: "samtools/samtools_idxstats"
  repository:
    type: "local"
- name: "umitools/umitools_dedup"
  repository:
    type: "local"
- name: "umitools_prepareforquant"
  repository:
    type: "local"
- name: "salmon/salmon_quant"
  repository:
    type: "local"
- name: "rsem/rsem_calculate_expression"
  repository:
    type: "local"
runners:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
engines:
- type: "native"
  id: "native"
build_info:
  config: "src/workflows/genome_alignment_and_quant/config.vsh.yaml"
  runner: "nextflow"
  engine: "native"
  output: "target/nextflow/workflows/genome_alignment_and_quant"
  executable: "target/nextflow/workflows/genome_alignment_and_quant/main.nf"
  viash_version: "0.9.0-RC2"
  git_commit: "f1bac79d3ebb4bff084f592da4371d1e3a1a6865"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh"
package_config:
  info: null
  viash_version: "0.9.0-RC2"
  source: "src"
  target: "target"
  config_mods:
  - ".version := 'dev'\n.requirements.commands := ['ps']\n.engines[.type == 'docker'].target_registry\
    \ := 'ghcr.io'\n.engines[.type == 'docker'].target_organization := 'data-intuitive'\n\
    .engines[.type == 'docker'].target_image_source := 'https://github.com/data-intuitive/rnaseq.vsh'\n\
    .runners[.type == 'nextflow'].directives.tag := '$id'\n.runners[.type == 'nextflow'].auto.simplifyOutput\
    \ := false"
  - ".version := \"main_build\""
