functionality:
  name: "genome_alignment_and_quant"
  namespace: "workflows"
  version: "dev"
  arguments:
  - type: "string"
    name: "--id"
    description: "ID of the sample."
    info: null
    example:
    - "foo"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--fastq_1"
    alternatives:
    - "-i"
    description: "Path to the sample (or read 1 of paired end sample)."
    info: null
    example:
    - "input.fastq.gz"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--fastq_2"
    description: "Path to read 2 of the sample."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--strandedness"
    description: "Sample strand-specificity. Must be one of unstranded, forward, reverse\
      \ or auto"
    info: null
    default:
    - "auto"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--gtf"
    description: "GTF file"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--transcript_fasta"
    description: "Fasta file of the reference transcriptome."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--star_index"
    description: "STAR index directory."
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--star_ignore_sjdbgtf"
    description: "When using pre-built STAR indices do not re-extract and use splice\
      \ junctions from the GTF file"
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--seq_platform"
    description: "Sequencing platform."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--seq_center"
    description: "Sequencing center."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--extra_star_align_args"
    description: "Extra arguments to pass to STAR alignment command in addition to\
      \ defaults defined by the pipeline."
    info: null
    default:
    - ""
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--bam_csi_index"
    description: "Create a CSI index for BAM files instead of the traditional BAI\
      \ index. This will be required for genomes with larger chromosome sizes."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--umi_dedup_stats"
    description: "Generate output stats when running \"umi_tools dedup\"."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--with_umi"
    description: "Enable UMI-based read deduplication."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--salmon_quant_libtype"
    description: "Override Salmon library type inferred based on strandedness defined\
      \ in meta object."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--extra_salmon_quant_args"
    description: "Extra arguments to pass to salmon quant command in addition to defaults\
      \ defined by the pipeline."
    info: null
    default:
    - ""
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--gtf_group_features"
    description: "Define the attribute type used to group features in the GTF file\
      \ when running Salmon."
    info: null
    default:
    - "gene_id"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--gtf_extra_attributes"
    description: "By default, the pipeline uses the gene_name field to obtain additional\
      \ gene identifiers from the input GTF file when running Salmon."
    info: null
    default:
    - "gene_name"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--star_alignment"
    info: null
    default:
    - "$id.STAR"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--star_multiqc"
    info: null
    default:
    - "$id.star_align.log"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--genome_bam_sorted"
    info: null
    default:
    - "$id.genome.bam"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--genome_bam_index"
    info: null
    default:
    - "$id.genome.bam.bai"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--genome_bam_stats"
    info: null
    default:
    - "$id.genome.stats"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--genome_bam_flagstat"
    info: null
    default:
    - "$id.genome.flagstat"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--genome_bam_idxstats"
    info: null
    default:
    - "$id.genome.idxstats"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--transcriptome_bam_sorted"
    info: null
    default:
    - "$id.transcriptome.bam"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--transcriptome_bam_index"
    info: null
    default:
    - "$id.transcriptome.bam.bai"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--transcriptome_bam_stats"
    info: null
    default:
    - "$id.transcriptome.stats"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--transcriptome_bam_flagstat"
    info: null
    default:
    - "$id.transcriptome.flagstat"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--transcriptome_bam_idxstats"
    info: null
    default:
    - "$id.transcriptome.idxstats"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--salmon_quant_results"
    info: null
    default:
    - "$id.salmon_quant"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  description: "A viash sub-workflow for genome alignment and quantification stage\
    \ of nf-core/rnaseq pipeline.\n"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  dependencies:
  - name: "star/star_align"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/star/align/config.vsh.yaml"
    configInfo:
      functionalityName: "star_align"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/star/align/config.vsh.yaml"
      functionalityNamespace: "star"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/star/star_align/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/star/star_align"
  - name: "samtools/samtools_sort"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/sort/config.vsh.yaml"
    configInfo:
      functionalityName: "samtools_sort"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/sort/config.vsh.yaml"
      functionalityNamespace: "samtools"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/samtools/samtools_sort/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/samtools/samtools_sort"
  - name: "samtools/samtools_index"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/index/config.vsh.yaml"
    configInfo:
      functionalityName: "samtools_index"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/index/config.vsh.yaml"
      functionalityNamespace: "samtools"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/samtools/samtools_index/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/samtools/samtools_index"
  - name: "samtools/samtools_stats"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/stats/config.vsh.yaml"
    configInfo:
      functionalityName: "samtools_stats"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/stats/config.vsh.yaml"
      functionalityNamespace: "samtools"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/samtools/samtools_stats/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/samtools/samtools_stats"
  - name: "samtools/samtools_flagstat"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/flagstat/config.vsh.yaml"
    configInfo:
      functionalityName: "samtools_flagstat"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/flagstat/config.vsh.yaml"
      functionalityNamespace: "samtools"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/samtools/samtools_flagstat/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/samtools/samtools_flagstat"
  - name: "samtools/samtools_idxstats"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/idxstats/config.vsh.yaml"
    configInfo:
      functionalityName: "samtools_idxstats"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/samtools/idxstats/config.vsh.yaml"
      functionalityNamespace: "samtools"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/samtools/samtools_idxstats/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/samtools/samtools_idxstats"
  - name: "umitools/umitools_dedup"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/umitools/dedup/config.vsh.yaml"
    configInfo:
      functionalityName: "umitools_dedup"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/umitools/dedup/config.vsh.yaml"
      functionalityNamespace: "umitools"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/umitools/umitools_dedup/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/umitools/umitools_dedup"
  - name: "umitools_prepareforquant"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/umitools_prepareforquant/config.vsh.yaml"
    configInfo:
      functionalityName: "umitools_prepareforquant"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/umitools_prepareforquant/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/umitools_prepareforquant/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/umitools_prepareforquant"
  - name: "salmon/salmon_quant"
    repository:
      type: "local"
      name: ""
      localPath: ""
    foundConfigPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/salmon/quant/config.vsh.yaml"
    configInfo:
      functionalityName: "salmon_quant"
      git_tag: ""
      git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
      viash_version: "0.8.0-RC5"
      config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/salmon/quant/config.vsh.yaml"
      functionalityNamespace: "salmon"
      output: ""
      platform: ""
      git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
      executable: "/nextflow/salmon/salmon_quant/main.nf"
    writtenPath: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/salmon/salmon_quant"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/nirmayi/data_intuitive/rnaseq.vsh/src/workflows/genome_alignment_and_quant/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/workflows/genome_alignment_and_quant"
  executable: "/home/nirmayi/data_intuitive/rnaseq.vsh/target/nextflow/workflows/genome_alignment_and_quant/main.nf"
  viash_version: "0.8.0-RC5"
  git_commit: "efa0ffd2fbdce950e208caa1570584b258689789"
  git_remote: "https://github.com/data-intuitive/rnaseq.vsh.git"
